### ISSUE TITLE
Expected fix for dynamoDB

### ISSUE THREAD

**Issue by pilsy** [chilts/awssum#110]
Hi,

In the AWSSUM api it requires Expected, even tho on the Amazon website it says it is Optional

**Comment by chilts** [comment]
Which operation please?

**Comment by chilts** [comment]
And which parameter?

**Comment by pilsy** [comment]
DeleteItem, i just figured out if i provide Expected: {} it kinda works?

**Comment by chilts** [comment]
Alright, fixed and pushed. Many thanks for raising the issue. :)

Cheers,
Andy

**Comment by pilsy** [comment]
Thanks for fixing it :) :+1:
