### ISSUE TITLE
PutObjectAcl and PutBucketAcl missing 'Content-Length' header

### ISSUE THREAD

**Issue by laddi** [chilts/awssum#111]
When calling PutObjectAcl or PutBucketAcl the Content-Length header is required.  These two methods should calculate the content-length from the body part of the put request and add it as a header when the request is made.

**Comment by laddi** [comment]
Actually figured out a good way to solve this by adding this to bodyAccessControlPolicy in s3-config.js:

```
var xml = data2xml('AccessControlPolicy', args.AccessControlPolicy);
options.headers['Content-Length'] = xml.length;

return xml;
```

**Comment by chilts** [comment]
Hi Laddi,

Fixed the Content-Length issue for you (slightly more generic way than your suggestion, but essentially the same thing).

Will cut a release later today. :)

Cheers,
Andy

**Comment by laddi** [comment]
Sweet! Then we can add two huge features to our console, instance resizing and ACL permission to storage objects! :)
