### ISSUE TITLE
Are there any concurrency limits

### ISSUE THREAD

**Issue by KalAvroniev** [chilts/awssum#117]
Hi,

I'm implementing SWF and I have to poll for multiple  taskLists, in my case 6 but it limits me to only 5.

What I do is I have a pooling function which polls for tasks and at the end it calls a callback which recalls the polling function. The problem is as soon as any of the code has to hit SWF the concurrency stops at  the first 5 and then it goes to the last one + 4 new ones and so on.

I've tried with simple code that has setTimeout and then calls the callback, no swf connection, and there I have no issues it works for all six.

I also checked the documentation for SWF and they say that you can run up to 10000 concurrent tasks so it makes me think it is a concurrency limit on your code.

I'm also experiencing the same problems with S3.

Can you please advice on what I can do?

**Comment by KalAvroniev** [comment]
One more thing concerning SWF, I was not able to create a domain using it.

**Comment by chilts** [comment]
You're hitting the default UserAgent limits.

Take a look at the following:
- https://github.com/appsattic/node-awssum/issues/18
- http://nodejs.org/api/all.html#all_class_http_agent

You'll need to make your own agent and pass it in.

Cheers,
Andy

P.S. As for your other issue, please raise a separate bug detailing what you did, what you passed and what the error was. Thanks.

**Comment by KalAvroniev** [comment]
Duuuuuh

Thanks :)

**Comment by chilts** [comment]
No worries. :)

Let me know how you get on since I'm not sure how many people are doing this. I'd love to hear that it is working for you fine.

/me should also add it to the docs

Cheers,
Andy
