### ISSUE TITLE
PutBucketLifecycle fails with 'Missing required header for this request: Content-MD5'

### ISSUE THREAD

**Issue by yuvaldrori** [chilts/awssum#122]
Same code, after npm update from 0.6.1 to 0.12
https://github.com/yuvaldrori/sfs/blob/master/server/index.js

**Comment by chilts** [comment]
I've just done a new release v0.12.1. Would it be possible to upgrade and try again please?

I think you've encountered an error caused by a previous error which I hope to have now fixed. :)

Cheers,
Andy

**Comment by yuvaldrori** [comment]
Hi Andy, I updated the module and the PutBucketLifeCycle works again but the PutBucketCors which I do right after, returns with the same error about not having the MD5 header - is it me using the CORS command wrong?
Thanks!!

**Comment by chilts** [comment]
Hi Yuval,

Yep, you're right, the PutBucketCors was incorrect since it wasn't adding the Content-MD5 to the request. Sorry about that. Amazing how inconsistent the S3 API is ... some of those PutBucket_Thing_ has the MD5, others the Content-Length, some both some neither! :D

Thanks for your help.

Cheers,
Andy

**Comment by yuvaldrori** [comment]
Hi Andy - thank you! I will test it later today to make sure.

**Comment by chilts** [comment]
Excellent, thanks. :)

**Comment by yuvaldrori** [comment]
Hi again Andy - so the MD5 issue is fixed! but i encountered another problem:
var cors = {'CORSRule':{
  'AllowedOrigin' : '_',
  'AllowedMethod' : 'POST',
  'AllowedMethod' : 'PUT',
  'AllowedMethod' : 'GET',
  'AllowedHeader' : '_',
  'MaxAgeSeconds' : '3000'
}}
If this is my CORS config, it will show only the 'AllowedMethod' : 'GET' in s3, is it possible that somehow only the last one gets passed?

**Comment by yuvaldrori** [comment]
Hello again Andy - everything works perfectly! I found how to define multiple nodes reading the data2xml readme...
Thanks for these great modules!!
