### ISSUE TITLE
ELB in VPC no supported

### ISSUE THREAD

**Issue by Gpx** [chilts/awssum#129]
I tried to register an EC2 instance on a Load Balancer, this is the error I get:

``` JSON
{
 "StatusCode":400,
 "Headers":{
  "x-amzn-requestid":"24f246c0-395f-11e2-a163-b3ff825fbe51",
  "content-type":"text/xml",
  "content-length":"346",
  "date":"Wed, 28 Nov 2012 13:25:57 GMT"
 },
 "Body":{
  "ErrorResponse":{
   "@":{
    "xmlns":"http://elasticloadbalancing.amazonaws.com/doc/2011-08-15/"
  },
  "Error":{
   "Type":"Sender",
   "Code":"ValidationError",
   "Message":"ELB in VPC is not supported in this version of API. Please try 2011-11-15 or newer."
  },
  "RequestId":"24f246c0-395f-11e2-a163-b3ff825fbe51"
  }
 }
}
```

I didn't find a way to change the API version. Are they going to be updated anytime soon?

Node version: 0.8.9
Awssum version: 0.12.1

**Comment by techtribe** [comment]
I do not have a VPC setup, so could you help out by going to your project directory and then

```
     ./node_modules/awssum/lib/amazon/elb.js
```

and replace 

``` javascript
var version = '2011-08-15';
```

with 

``` javascript
var version = '2011-11-15';
```

Could you let us know if this helps you? Then I know if your issue is only about the version or also the way you use awssum.

Thanks in advance.

:)

**Comment by Gpx** [comment]
I changed the line and it works, thanks. Are you going to change the version in the master branch?

**Comment by techtribe** [comment]
fixed it in master, but not yet in npm (@chilts when do you want to update to 0.12.1?)

**Comment by Gpx** [comment]
Meanwhile I'll use the git version in my project.

Thanks for the support!

**Comment by chilts** [comment]
Hey guys,

Firstly, thanks @Techtribe for fixing. :) Once the commit is in master, the issue should be closed.

Once that's done, we need to figure out if this is a fix which needs to be done to the current release. I'd say in this case that it should ... I'm happy to cut a new release today. I'll cherry pick this commit only to the v0.12 branch and set a new patch level.

Thanks Giorgio for reporting.

Cheers,
Andy

**Comment by Gpx** [comment]
Thanks both.
