### ISSUE TITLE
Pre-Sign Amazon Requests

### ISSUE THREAD

**Issue by robraux** [chilts/awssum#130]
Apologies if it's listed somewhere, I've poured through the documentation and existing issues and don't see it.

How do you generate a pre-signed URL? I don't want to act on the URL, simply generate it and pass it back to a front-end client. 

My end goal looks like this:
1.  Generate pre-signed PUT object URL using awssum and return to front end browser.
2. Allow in browser javascript to use pre-signed, coupled with the Amazon CORS support, to PUT the object directly from the user, into S3.

Can someone point me in the right direction for generating this URL with awssum?

**Comment by chilts** [comment]
Just so I can use this for info: http://docs.amazonwebservices.com/AmazonCloudFront/latest/DeveloperGuide/CreateURLPerl.html

**Comment by chilts** [comment]
Also http://kitcarrau.tumblr.com/post/12841485836/amazon-s3-signed-urls-with-nodejs

**Comment by robraux** [comment]
Knox also does it already: https://github.com/LearnBoost/knox/blob/master/lib/client.js (see: signedUrl)

**Comment by jothirams** [comment]
@chilts

It will be very helpful if awssum can generate this URL. Do you have any plans to add the same.

**Comment by chilts** [comment]
AwsSum is now deprecated in favour of the offical aws-sdk from Amazon. Thanks for opening this originally.
