### ISSUE TITLE
Body returned empty on glacier.InitiateJob

### ISSUE THREAD

**Issue by PierrickP** [chilts/awssum#134]
On Glacier service.

I try to list archives on my vault.

``` JavaScript
glacier.InitiateJob({
    VaultName: vault,
    Type: 'archive-retrieval'
}, function(err, data){
        // err.Header.StatusCode == 404
        // err.Body == ''
});
```

i receive an 404 error and i don''t know why.
After activate debug (an setter would be a good idea), my `err.Body` are finally not empty.
And i have precious information like `err.Body.Code` [doc aws error](http://docs.amazonwebservices.com/amazonglacier/latest/dev/api-error-responses.html) and message !

It's probably better if there aren't `extractBody : none`

Finally, my vault was too young for archive retrieval

**Comment by chilts** [comment]
Initiate job has no body in the response:
- http://docs.amazonwebservices.com/amazonglacier/latest/dev/api-initiate-job-post.html

If you want to list your jobs, then you need to do a ListJobs:
- http://docs.amazonwebservices.com/amazonglacier/latest/dev/api-jobs-get.html

Cheers,
Andy
