### ISSUE TITLE
ability to pipe a stream into putObject

### ISSUE THREAD

**Issue by jpstrikesback** [chilts/awssum#14]
How would one send a pipe of a download stream (via node-cloudfiles) from request into putObject? Node-cloudfiles can send Content-Length so it should be doable theoretically right?

**Comment by chilts** [comment]
Yes, this should be possible though I haven't tried it.

Note, since this isn't an issue (it's a question), I'm closing it. Feel free to send me an email or contact me any other way. Sorry, I missed your irc question since I was away at the time.
