### ISSUE TITLE
Can't set logging status on buckets

### ISSUE THREAD

**Issue by ddollar** [chilts/awssum#142]
https://github.com/appsattic/node-awssum/blob/master/lib/amazon/s3-config.js#L149-L158

These lines seem to overwrite any changes made by the TargetBucket/TargetPrefix lines above.

**Comment by chilts** [comment]
You're totally right! Sorry about that. :)

I'm gonna fix a few things up later today, and will publish to npm after that.

**Comment by chilts** [comment]
Can you try this again please. I've fixed it over in the new repo for awssum-amazon-s3. Let me know how it goes (and re-raise an issue over there please):
- https://github.com/awssum/awssum-amazon-s3/commit/651e0bf19400bc43b6f77fdd1f234be909ddbf90

Released to npm in v1.1.0. :)
