### ISSUE TITLE
S3 ListObject Options problem

### ISSUE THREAD

**Issue by ondrek** [chilts/awssum#144]
Hello,

I use the newest Awssum and I am trying to get List of objects in my bucket.
It works.
But when I set options with MaxKeys or Prefix or Marker, 
It just ignores options and gets full list of all Keys again.

In my testcase is existing sample, bucket and credentials. 

Your Sample
https://github.com/appsattic/node-awssum/blob/master/examples/amazon/s3/list-objects.js

My Testcase
https://gist.github.com/4468232

Thx

**Comment by chilts** [comment]
@ondrek Ah sorry. Can you paste your code here so I can take a look.

Cheers,
Andy

**Comment by chilts** [comment]
Since AwsSum is now unsupported (use the aws-sdk from Amazon instead), I'll just close this out.
