### ISSUE TITLE
Support for IAM Instance Profiles

### ISSUE THREAD

**Issue by devdazed** [chilts/awssum#145]
It would be nice if there was support for IAM instance profiles.  This is different than the `GetInstanceProfile` endpoint.  The Instance profiles allow an instance access to resources, rather than a user.  The AccessKeyId and Secret change frequently so it would need to check and update prior to expiration. 

To get the data manually you would do:

```
curl http://169.254.169.254/latest/meta-data/iam/security-credentials/my-iam-group-name
```

which gives you a response similar to:

``` json
{
  "Code" : "Success",
  "LastUpdated" : "2013-01-08T18:17:31Z",
  "Type" : "AWS-HMAC",
  "AccessKeyId" : "ACCESS KEY ID IS HERE",
  "SecretAccessKey" : "SSSHHHH ITS A SECRET",
  "Token" : "SECRET TOKEN IS HERE TOO",
  "Expiration" : "2013-01-09T00:43:23Z"
}

```

It would be awesome to support this type of auth, especially if it can be just turned on with a flag.

**Comment by techtribe** [comment]
Could you elaborate what you want differently? As I've been working with instance profiles I first needed to make a instance profile and then add to every EC2 instance this IAM-instance-profile, to make it possible to grab security credentials inside the EC2-instance using a time-based mechanism that repeats this process every x-minutes.

As far as I see now, you could do that already, but are you asking for a new feature or do you want documentation how to do this exactly?

**Comment by devdazed** [comment]
right now I am going a manual http GET to the URL to get the credentials.  Is there already a way to do this in awssum? If there is already a way to get the IAM-instance-profile credentials (without providing your own credentials) then the documentation would be sufficient.  

If there isn't a way to do this via awssum, then I think it would be a great feature.

**Comment by techtribe** [comment]
Yup, [IMD](http://awssum.io/amazon/imd/) provides this through Awssum. See [this](http://awssum.io/amazon/imd/get.html) for an example. Replace 

``` javascript
Category : /
```

with

``` javascript
Category : /iam/security-credentials/your_role_name
```

FYI & I will update the docs soon for this situation. Let me know if you see any issues with that or new feature requests.

**Comment by techtribe** [comment]
A correct example

``` javascript
var params = {
    Version  : 'latest',
    Category : '/meta-data/iam/security-credentials/your_iam_role_name'
};
imd.Get(params,function(err, data) {
    fmt.dump(err, 'Error');
    fmt.dump(data, 'Data');
});
```

it will provide an object with AccessKeyId, SecretAccessKey, SessionToken, and Expiration variables.

let me know if this fails.

**Comment by devdazed** [comment]
this worked beautifully, thanks!
