### ISSUE TITLE
CopyObject doesn't send headers when replacing

### ISSUE THREAD

**Issue by NeoPhi** [chilts/awssum#147]
When issuing a CopyObject request with a MetadataDirective of REPLACE awssum doesn't include in the request all of the standard headers that one can specify with a PutObject request such as CacheControl, ContentType, MetaData, etc. It looks like these other headers just need to be copied from the PutObject definition in s3-config.js.

**Comment by chilts** [comment]
Hi Daniel,

Thanks for raising this issue.

I just had a read of the docs : http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html

Unfortunately, I can't see other things this operation supports. I think you're completely right that you should be able to do things like CacheControl much like PutObject, but I can't see an example. Did you see it somewhere else (and if so, can you point me to it)?

Many thanks,
Andy

**Comment by NeoPhi** [comment]
My understanding of how it should work based on the document that you linked to is as follows.

Under the documentation for `x-amz-metadata-directive` it mentions that "If replaced, all original metadata is replaced by the metadata you specify."

In particular when trying to update the metadata on an existing object it calls out "You cannot copy an object to itself unless the MetadataDirective header is specified and its value set to REPLACE."

Lastly it mentions that "For information on supported metadata, see Common Request Headers". In looking at http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html (the linked to document) it includes Content-Length, Content-Type, etc.

**Comment by chilts** [comment]
Since AwsSum is now unsupported (use the aws-sdk from Amazon instead), I'll just close this out.
