### ISSUE TITLE
PutBucketWebsite is missing ContentLength header to work on GreenQloud (fix included)

### ISSUE THREAD

**Issue by sputnick** [chilts/awssum#148]
Hey Andy,

I debugged PutBucketWebsite and just like the PutAcl methods it needs the content length. I added the extras option in line 1239 of s3-config.js and then it worked. We now have static website support from Storage Qloud buckets :)
...
        body : bodyWebsiteConfiguration,
        addExtras : extrasContentLength,
...

Can you make that one line change in master?

cheers
Eiki
GreenQloud

**Comment by sputnick** [comment]
It would be great to get this into master asap so we can update our servers...

cheers
Eiki

**Comment by chilts** [comment]
Hi Eiki,

It's such a minor change ... but it would be quicker if you were to create a pull request.

I'm currently working pretty long hours on something I get paid to do. They have my attention and priority. This is an unpaid project I work on on the side. If you can help it from the point of view of a company using it to make money, then a pull request would be greatly appreciated. :)

Cheers,
Andy

**Comment by sputnick** [comment]
Will do buddy :)

Eirikur Hrafnsson - @EirikurH
Founder & Chief Global Strategist
@GreenQloud - http://greenqloud.com

**Comment by chilts** [comment]
Fixed in the new awssum/awssum-amazon-s3.
- https://github.com/awssum/awssum-amazon-s3/commit/e46f56044a0da5d5de39093f8868059e86019fa2

Released as v1.0.1.
