### ISSUE TITLE
Stream Support for S3 GetObject

### ISSUE THREAD

**Issue by danhstevens** [chilts/awssum#150]
The [example here](https://github.com/appsattic/node-awssum/blob/master/examples/amazon/s3/get-object-stream.js) shows how to enable streaming of an S3 object when calling GetObject. However, that doesn't seem to actually be implemented and when calling GetObject with `stream: true` it seems to be ignored. How can you stream an object from S3 using awssum?

**Comment by jamesbrucepower** [comment]
Yes I had this problem too, the solution I use it don't npm install awssum, use git clone in your node_modules directory, it seems the streaming support hasn't been committed as a version yet

**Comment by chilts** [comment]
There is now streaming support in awssum-amazon-s3 (well, in AwsSum v1.0.0-beta, but it'll come through with awssum-amazon-s3).

```
$ npm install awssum-amazon-s3
```

Please take a look at the README here -> https://github.com/awssum/awssum-amazon-s3/

Just depend on awssum-amazon-s3 in your package.json and you should be able to do streaming uploads and downloads. :)

Thanks guys and let me know how you get on.

Cheers,
Andy
