### ISSUE TITLE
ModifyInstanceAttribute does not work

### ISSUE THREAD

**Issue by roddik** [chilts/awssum#151]
Here https://github.com/appsattic/node-awssum/blob/master/lib/amazon/ec2-config.js#L1442 it says `BlockMappingDevice` instead of `BlockDeviceMapping`, so it does not add the device mapping to the request. The documentation for that is missing as well, though I could get it working like this after fixing the BlockDeviceMapping issue.

```
ec2.ModifyInstanceAttribute({
    InstanceId: "i-eaxxxxx",
    BlockDeviceMapping: [
        {
            "DeviceName": "/dev/sdx",
            "Ebs": [{
                "DeleteOnTermination": "true",
                "VolumeId": "vol-59xxxxx"
            }]
        }
    ]
}, function(err, body) {
```

**Comment by chilts** [comment]
Hi Rodion,

Thanks for this and for digging into the correct parameter name. :)

Cheers,
Andy

**Comment by roddik** [comment]
Thanks Andy. When will it be published to npm?
