### ISSUE TITLE
Region not set to EU-WEST-1 in the '...-europe.js' examples

### ISSUE THREAD

**Issue by FreeLiveTutor** [chilts/awssum#153]
Some of the examples/amazon/s3 have the region set as US rather than the EU

eg.
list-objects-europe.js line 14
list-buckets-europe.js line 15

should be : 
'region' : amazon.EU_WEST_1

or maybe I've missed the point of the tests in which case let me know, as am keen on these functions!

**Comment by chilts** [comment]
I think you're right.

However, I've changed the repos around to a plugin architecture and I think these examples aren't there anymore. I should resurrect them. Sorry about that.

Anyway, issue acknowledged. :)

**Comment by chilts** [comment]
AwsSum is now deprecated in favour of the offical aws-sdk from Amazon. Thanks for opening this originally.
