### ISSUE TITLE
S3 Object Restore

### ISSUE THREAD

**Issue by geoffreak** [chilts/awssum#158]
Any chance of the [restore logic for S3](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOSTrestore.html) coming to Awssum? (or am I missing where it is?)

**Comment by chilts** [comment]
Yeah, sounds good. I hadn't seen that. Any chance you could open an issue at https://github.com/awssum/awssum-amazon-s3 instead of here?

Thanks,
Andy
