### ISSUE TITLE
Is x-amz-request-payer request header supported?

### ISSUE THREAD

**Issue by mitar** [chilts/awssum#159]
I would like to use awssum to access [requester payer](http://docs.aws.amazon.com/AmazonS3/latest/dev/RequesterPaysBuckets.html) S3 bucket. It requires to set `x-amz-request-payer` as a parameter when requesting an object. Is this supported or are just [params listed here](http://awssum.io/amazon/s3/get-object.html) supported?

**Comment by chilts** [comment]
This has now been added to https://github.com/awssum/awssum-amazon-s3/ and released as awssum-amazon-s3 (v1.2.4).

It won't be backported to AwsSum v0.12.2 so please use the new plugin architecture. :)

I've added the RequestPayer param to GetObject. I tried to find out in the docs if there was an equivalent for PutObject but couldn't. I hope that's all bases covered.

Cheers,
Andy

**Comment by mitar** [comment]
Vau, that was fast. Thanks!
