### ISSUE TITLE
AWSSUM 1.0.0 Beta breaks 

### ISSUE THREAD

**Issue by fizerkhan** [chilts/awssum#160]
```
"Error: Cannot find module './amazon/amazon'",
"    at Function.Module._resolveFilename (module.js:338:15)",
"    at Function.Module._load (module.js:280:25)",
"    at Module.require (module.js:362:17)",
"    at require (module.js:378:17)",
"    at Object.load (/Users/guest/development/git/myproject/node_modules/awssum/awssum.js:43:12)",
"    at Object.<anonymous> (/Users/guest/development/git/myproject/server/lib/aws/index.js:11:23)",
"    at Module._compile (module.js:449:26)",
"    at Object.Module._extensions..js (module.js:467:10)",
"    at Module.load (module.js:356:32)",
"    at Function.Module._load (module.js:312:12)"
```

**Comment by chilts** [comment]
I have no idea what version of AwsSum you're using or how you're using it. Please provide more info.

**Comment by fizerkhan** [comment]
@chilts Thanks. I use 1.0.0 Beta. But i did not aware of new plugin architecture. Now it works with new plugin architecture. 
It will be good if there is any migration steps for old version(< 1.0.0) users.

**Comment by chilts** [comment]
Ok, thanks. I'll look at putting something on the main awssum/awssum page. Cheers. :)

**Comment by fizerkhan** [comment]
Thanks mate :+1:

**Comment by inadarei** [comment]
Um, to clarify this issue further, this is what should be in package.json if you are using say S3 and SQS modules:

```
, "dependencies": {
    "awssum"            : "1.x"
  , "awssum-amazon-sqs" : "1.x"
  , "awssum-amazon-s3": "1.x"
  }
```

AND this is how you should initialize variables, INSTEAD of what the current documentation at awssum.io tells you about the module.load() thingie:

```
var awssum = require('awssum')
    , amazon = require('awssum-amazon')
    , S3 = require('awssum-amazon-sqs').S3;
    , Sqs = require('awssum-amazon-sqs').Sqs;
```
