### ISSUE TITLE
s3.CheckBucket callback params are backwards

### ISSUE THREAD

**Issue by inadarei** [chilts/awssum#165]
Instead of passing (err, data) to the callback, the callback clearly gets (data, err).

Using version: 1.2.4

**Comment by chilts** [comment]
Hi Irakli,

Can you let me know where this is please. Sorry, I can't seem to find it. I'm guessing this should be against the https://github.com/awssum/awssum-amazon-s3/ repo.

Cheers,
Andy

**Comment by chilts** [comment]
No further evidence. Closing.
