### ISSUE TITLE
Travis build is a month old

### ISSUE THREAD

**Issue by ben-biddington** [chilts/awssum#19]
Hi,

Has this project had [its connector](http://travis-ci.org/profile) removed? Its last build passed, but that was a month ago and I get several test failures from 2dcf39e684f4e0444bfee726ea638d32651c5de4.

<bb />

**Comment by chilts** [comment]
Hiya,

Yes, I've noticed this too. I had checked the connector the other day and it seems fine.

From what I can tell, my tests hang when I run them locally and so I suspect that travis also hangs and we never get a result. In my opinion that should make travis fail.

Do you get this same problem (it hanging) or other errors? Can you paste your output here?

Many thanks for your report. It'll nudge me to do something. :)

Cheers,
chilts

**Comment by ben-biddington** [comment]
I don't get hanging, no:

HEAD => 2dcf39e684f4e0444bfee726ea638d32651c5de4
node v0.6.15
`npm install` completed okay

# 

> awssum@0.4.1 test /home/ben/sauce/node-awssum
> tap test/

not ok test/amazon.js .................................. 7/12
    Command: "node" "amazon.js"
    TAP version 13
    ok 1 object loaded
    ok 2 US East 1
    ok 3 US West 1
    ok 4 EU West 1
    ok 5 AP SouthEast 1
    ok 6 AP NorthEast 1
    not ok 7 undefined: undefined
      ---
        type:    ~
        message: ~
        code:    ~
        errno:   ~
        stack:  
          - 
        thrown:  true
      ...
    not ok 8 undefined: undefined
      ---
        type:    ~
        message: ~
        code:    ~
        errno:   ~
        stack:  
          - 
        thrown:  true
      ...
    not ok 9 undefined: undefined
      ---
        type:    ~
        message: ~
        code:    ~
        errno:   ~
        stack:  
          - 
        thrown:  true
      ...
    not ok 10 undefined: undefined
      ---
        type:    ~
        message: ~
        code:    ~
        errno:   ~
        stack:  
          - 
        thrown:  true
      ...
    not ok 11 undefined: undefined
      ---
        type:    ~
        message: ~
        code:    ~
        errno:   ~
        stack:  
          - 
        thrown:  true
      ...
    ok 12 test/amazon.js

```
1..12
# tests 12
# pass  7
# fail  5
```

ok test/awssum.js ....................................... 2/2
ok test/elasticache.js .................................. 3/3
not ok test/escape.js ................................... 0/1
    Command: "node" "escape.js"
    TAP version 13
    not ok 1 test/escape.js
      ---
        timedOut: ~
        exit:     1
        stderr:   |
          node.js:201
                  throw e; // process.nextTick error, or 'error' event on first tick
                        ^
          Error: Cannot find module '../lib/escape.js'
              at Function._resolveFilename (module.js:332:11)
              at Function._load (module.js:279:25)
              at Module.require (module.js:354:17)
              at require (module.js:370:17)
              at Object.<anonymous> (/home/ben/sauce/node-awssum/test/escape.js:4:14)
              at Module._compile (module.js:441:26)
              at Object..js (module.js:459:10)
              at Module.load (module.js:348:31)
              at Function._load (module.js:308:12)
              at Array.0 (module.js:479:10)
        command:  "node" "escape.js"
      ...

```
1..1
# tests 1
# fail  1
```

not ok test/s3-streaming.js ............................. 1/5
    Command: "node" "s3-streaming.js"
    TAP version 13
    not ok 1 TypeError: object is not a function
      ---
        type:    TypeError
        message: object is not a function
        code:    called_non_callable
        errno:   ~
        file:    /home/ben/sauce/node-awssum/test/s3-streaming.js
        line:    36
        column:  14
        stack:  
          - Object.CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
          - Test.<anonymous> (/home/ben/sauce/node-awssum/test/s3-streaming.js:36:14)
          - Test.<anonymous> (native)
          - Test.<anonymous> (events.js:88:20)
          - Test.emit (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:103:8)
          - GlobalHarness.<anonymous> (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:86:13)
          - Array.0 (native)
          - EventEmitter._tickCallback (node.js:192:40)
        thrown:  true
      ...
    not ok 2 test count != plan
      ---
        file:   node.js
        line:   192
        column: 40
        stack:  
          - getCaller (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-assert.js:415:17)
          - assert (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-assert.js:20:16)
          - Function.equal (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-assert.js:161:10)
          - Test.end (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:116:31)
          - Test.threw (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:49:8)
          - Test.emit (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:107:10)
          - GlobalHarness.<anonymous> (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:86:13)
          - Array.0 (native)
          - EventEmitter._tickCallback (node.js:192:40)
        found:  1
        wanted: 4
      ...
    not ok 3 TypeError: object is not a function
      ---
        type:    TypeError
        message: object is not a function
        code:    called_non_callable
        errno:   ~
        file:    /home/ben/sauce/node-awssum/test/s3-streaming.js
        line:    100
        column:  14
        stack:  
          - Object.CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
          - Test.<anonymous> (/home/ben/sauce/node-awssum/test/s3-streaming.js:100:14)
          - Test.<anonymous> (native)
          - Test.<anonymous> (events.js:88:20)
          - Test.emit (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:103:8)
          - GlobalHarness.<anonymous> (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:86:13)
          - Array.0 (native)
          - EventEmitter._tickCallback (node.js:192:40)
        thrown:  true
      ...
    not ok 4 test count != plan
      ---
        file:   node.js
        line:   192
        column: 40
        stack:  
          - getCaller (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-assert.js:415:17)
          - assert (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-assert.js:20:16)
          - Function.equal (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-assert.js:161:10)
          - Test.end (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:116:31)
          - Test.threw (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:49:8)
          - Test.emit (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:107:10)
          - GlobalHarness.<anonymous> (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:86:13)
          - Array.0 (native)
          - EventEmitter._tickCallback (node.js:192:40)
        found:  1
        wanted: 3
      ...
    ok 5 test/s3-streaming.js

```
1..5
# tests 5
# pass  1
# fail  4
```

not ok test/s3.js ....................................... 3/7
    Command: "node" "s3.js"
    TAP version 13
    ok 1 object loaded
    ok 2 object loaded
    not ok 3 TypeError: object is not a function
      ---
        type:    TypeError
        message: object is not a function
        code:    called_non_callable
        errno:   ~
        file:    /home/ben/sauce/node-awssum/test/s3.js
        line:    37
        column:  14
        stack:  
          - Object.CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
          - Test.<anonymous> (/home/ben/sauce/node-awssum/test/s3.js:37:14)
          - Test.<anonymous> (native)
          - Test.<anonymous> (events.js:88:20)
          - Test.emit (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:103:8)
          - GlobalHarness.<anonymous> (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:86:13)
          - Array.0 (native)
          - EventEmitter._tickCallback (node.js:192:40)
        thrown:  true
      ...
    not ok 4 TypeError: object is not a function
      ---
        type:    TypeError
        message: object is not a function
        code:    called_non_callable
        errno:   ~
        file:    /home/ben/sauce/node-awssum/test/s3.js
        line:    48
        column:  15
        stack:  
          - Object.CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
          - Test.<anonymous> (/home/ben/sauce/node-awssum/test/s3.js:48:15)
          - Test.<anonymous> (native)
          - Test.<anonymous> (events.js:88:20)
          - Test.emit (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:103:8)
          - GlobalHarness.<anonymous> (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:86:13)
          - Array.0 (native)
          - EventEmitter._tickCallback (node.js:192:40)
        thrown:  true
      ...
    not ok 5 TypeError: object is not a function
      ---
        type:    TypeError
        message: object is not a function
        code:    called_non_callable
        errno:   ~
        file:    /home/ben/sauce/node-awssum/test/s3.js
        line:    64
        column:  14
        stack:  
          - Object.CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
          - Test.<anonymous> (/home/ben/sauce/node-awssum/test/s3.js:64:14)
          - Test.<anonymous> (native)
          - Test.<anonymous> (events.js:88:20)
          - Test.emit (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:103:8)
          - GlobalHarness.<anonymous> (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:86:13)
          - Array.0 (native)
          - EventEmitter._tickCallback (node.js:192:40)
        thrown:  true
      ...
    not ok 6 TypeError: object is not a function
      ---
        type:    TypeError
        message: object is not a function
        code:    called_non_callable
        errno:   ~
        file:    /home/ben/sauce/node-awssum/test/s3.js
        line:    150
        column:  14
        stack:  
          - Object.CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
          - Test.<anonymous> (/home/ben/sauce/node-awssum/test/s3.js:150:14)
          - Test.<anonymous> (native)
          - Test.<anonymous> (events.js:88:20)
          - Test.emit (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:103:8)
          - GlobalHarness.<anonymous> (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:86:13)
          - Array.0 (native)
          - EventEmitter._tickCallback (node.js:192:40)
        thrown:  true
      ...
    ok 7 test/s3.js

```
1..7
# tests 7
# pass  3
# fail  4
```

ok test/ses.js .......................................... 3/3
not ok test/simpledb.js ................................. 3/6
    Command: "node" "simpledb.js"
    TAP version 13
    ok 1 object loaded
    ok 2 object loaded
    not ok 3 TypeError: object is not a function
      ---
        type:    TypeError
        message: object is not a function
        code:    called_non_callable
        errno:   ~
        file:    /home/ben/sauce/node-awssum/test/simpledb.js
        line:    37
        column:  15
        stack:  
          - Object.CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
          - Test.<anonymous> (/home/ben/sauce/node-awssum/test/simpledb.js:37:15)
          - Test.<anonymous> (native)
          - Test.<anonymous> (events.js:88:20)
          - Test.emit (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:103:8)
          - GlobalHarness.<anonymous> (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:86:13)
          - Array.0 (native)
          - EventEmitter._tickCallback (node.js:192:40)
        thrown:  true
      ...
    not ok 4 TypeError: object is not a function
      ---
        type:    TypeError
        message: object is not a function
        code:    called_non_callable
        errno:   ~
        file:    /home/ben/sauce/node-awssum/test/simpledb.js
        line:    48
        column:  16
        stack:  
          - Object.CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
          - Test.<anonymous> (/home/ben/sauce/node-awssum/test/simpledb.js:48:16)
          - Test.<anonymous> (native)
          - Test.<anonymous> (events.js:88:20)
          - Test.emit (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:103:8)
          - GlobalHarness.<anonymous> (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:86:13)
          - Array.0 (native)
          - EventEmitter._tickCallback (node.js:192:40)
        thrown:  true
      ...
    not ok 5 TypeError: object is not a function
      ---
        type:    TypeError
        message: object is not a function
        code:    called_non_callable
        errno:   ~
        file:    /home/ben/sauce/node-awssum/test/simpledb.js
        line:    64
        column:  15
        stack:  
          - Object.CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
          - Test.<anonymous> (/home/ben/sauce/node-awssum/test/simpledb.js:64:15)
          - Test.<anonymous> (native)
          - Test.<anonymous> (events.js:88:20)
          - Test.emit (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:103:8)
          - GlobalHarness.<anonymous> (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:86:13)
          - Array.0 (native)
          - EventEmitter._tickCallback (node.js:192:40)
        thrown:  true
      ...
    ok 6 test/simpledb.js

```
1..6
# tests 6
# pass  3
# fail  3
```

not ok test/sns.js ...................................... 3/5
    Command: "node" "sns.js"
    TAP version 13
    ok 1 object loaded
    ok 2 object loaded
    not ok 3 TypeError: object is not a function
      ---
        type:    TypeError
        message: object is not a function
        code:    called_non_callable
        errno:   ~
        file:    /home/ben/sauce/node-awssum/test/sns.js
        line:    37
        column:  15
        stack:  
          - Object.CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
          - Test.<anonymous> (/home/ben/sauce/node-awssum/test/sns.js:37:15)
          - Test.<anonymous> (native)
          - Test.<anonymous> (events.js:88:20)
          - Test.emit (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:103:8)
          - GlobalHarness.<anonymous> (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:86:13)
          - Array.0 (native)
          - EventEmitter._tickCallback (node.js:192:40)
        thrown:  true
      ...
    not ok 4 TypeError: object is not a function
      ---
        type:    TypeError
        message: object is not a function
        code:    called_non_callable
        errno:   ~
        file:    /home/ben/sauce/node-awssum/test/sns.js
        line:    48
        column:  16
        stack:  
          - Object.CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
          - Test.<anonymous> (/home/ben/sauce/node-awssum/test/sns.js:48:16)
          - Test.<anonymous> (native)
          - Test.<anonymous> (events.js:88:20)
          - Test.emit (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:103:8)
          - GlobalHarness.<anonymous> (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:86:13)
          - Array.0 (native)
          - EventEmitter._tickCallback (node.js:192:40)
        thrown:  true
      ...
    ok 5 test/sns.js

```
1..5
# tests 5
# pass  3
# fail  2
```

not ok test/sqs.js ...................................... 3/6
    Command: "node" "sqs.js"
    TAP version 13
    ok 1 object loaded
    ok 2 object loaded
    not ok 3 TypeError: object is not a function
      ---
        type:    TypeError
        message: object is not a function
        code:    called_non_callable
        errno:   ~
        file:    /home/ben/sauce/node-awssum/test/sqs.js
        line:    37
        column:  15
        stack:  
          - Object.CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
          - Test.<anonymous> (/home/ben/sauce/node-awssum/test/sqs.js:37:15)
          - Test.<anonymous> (native)
          - Test.<anonymous> (events.js:88:20)
          - Test.emit (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:103:8)
          - GlobalHarness.<anonymous> (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:86:13)
          - Array.0 (native)
          - EventEmitter._tickCallback (node.js:192:40)
        thrown:  true
      ...
    not ok 4 TypeError: object is not a function
      ---
        type:    TypeError
        message: object is not a function
        code:    called_non_callable
        errno:   ~
        file:    /home/ben/sauce/node-awssum/test/sqs.js
        line:    48
        column:  16
        stack:  
          - Object.CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
          - Test.<anonymous> (/home/ben/sauce/node-awssum/test/sqs.js:48:16)
          - Test.<anonymous> (native)
          - Test.<anonymous> (events.js:88:20)
          - Test.emit (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:103:8)
          - GlobalHarness.<anonymous> (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:86:13)
          - Array.0 (native)
          - EventEmitter._tickCallback (node.js:192:40)
        thrown:  true
      ...
    not ok 5 TypeError: object is not a function
      ---
        type:    TypeError
        message: object is not a function
        code:    called_non_callable
        errno:   ~
        file:    /home/ben/sauce/node-awssum/test/sqs.js
        line:    64
        column:  15
        stack:  
          - Object.CALL_NON_FUNCTION_AS_CONSTRUCTOR (native)
          - Test.<anonymous> (/home/ben/sauce/node-awssum/test/sqs.js:64:15)
          - Test.<anonymous> (native)
          - Test.<anonymous> (events.js:88:20)
          - Test.emit (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-test.js:103:8)
          - GlobalHarness.<anonymous> (/home/ben/sauce/node-awssum/node_modules/tap/lib/tap-harness.js:86:13)
          - Array.0 (native)
          - EventEmitter._tickCallback (node.js:192:40)
        thrown:  true
      ...
    ok 6 test/sqs.js

```
1..6
# tests 6
# pass  3
# fail  3
```

total ................................................. 28/50

not ok

**Comment by chilts** [comment]
Ah crap. Sorry about that. I haven't been running them since my tests had been hanging and all of that is due to a few recent commits in the past few days. I'm currently on lunch but will fix these on the train on the way home. :)

Will be done by later on tonight at the latest (about 10 hrs).

Many thanks ... funny thing is, my tests run again now so I can see the same errors as you. I tried after your paste to compare and it ran through the whole lot. Should be fairly straightforward to fix. :)

**Comment by ben-biddington** [comment]
Grouse!

<bb />

**Comment by chilts** [comment]
Righto, this has now been solved. Even though I never changed it, the 'username' in my hook was my email address and not 'chilts'. Very strange. I did 99 builds and suddenly it stopped.

The build is now up to 100 and passing! :)
- http://travis-ci.org/#!/appsattic/node-awssum

Thanks for raising this issue.
