### ISSUE TITLE
Error on S3 PutObject

### ISSUE THREAD

**Issue by ashchan** [chilts/awssum#2]
Calling:

```
var options = {
  BucketName    : 'pie-18',
  ObjectName    : 'test-object.txt',
  ContentLength : '14',
  Body          : "Hello, World!\n",
};

s3.PutObject(options, function(err, data) {});
```

Error:

```
[Error: First argument needs to be a number, array or string.]
```

The error happened on ln 365 of awssum.js:

```
    else if ( spec.type === 'header-base64' ) {
        setHeader( options.forms, name, (new Buffer(args[argName])).toString('base64') );
    }
```

More specified, when this happened argName was ContentMD5.

Node version is 0.6.7. Project's tests pass without any problem.

**Comment by chilts** [comment]
Thanks James ... I've just put v0.3.3 onto npm. :)

Silly me for changing that bit at the last minute last night!

**Comment by ashchan** [comment]
That's a quick fix! Thank you!

This project is very promising :)

**Comment by chilts** [comment]
Hi James,

No worries, glad I could help.

I'm also happy to hear any suggestions from users of the library, so don't be afraid to open any more issues/feature suggestions.

Andy
