### ISSUE TITLE
S3.PutObject has no provision for MetaData

### ISSUE THREAD

**Issue by aaronfay** [chilts/awssum#20]
(as per our email discussion)

The S3 interface has no current provision for adding custom headers to the PUT request.  Please implement ability to have meta!

Thanks Andy.

```
// example from your email
var body = "Hello, World!\n";
var optionsWithMetaData = {
   BucketName    : 'pie-18',
   ObjectName    : 'test-object-with-metadata.txt',
   MetaData      : {
       'User' : 'chilts'
   },
   ContentLength : Buffer.byteLength(body),
   Body          : body,
};
s3.PutObject(optionsWithMetaData, function(err, data) {
   console.log("\nputting an object with metadata to pie-18 -
expecting success");
   inspect(err, 'Error');
   inspect(data, 'Data');
});
```

**Comment by chilts** [comment]
Hi Aaron,

Thanks again for raising this issue and for figuring things out in our emails earlier. This is now fixed and if you'd like to see an example of using it, take a look here (much like the above):
- https://github.com/appsattic/node-awssum/blob/master/examples/amazon/s3/put-object.js

Thanks again,
Andy

**Comment by chilts** [comment]
v0.5.1 has just been pushed to NPM. :)

**Comment by aaronfay** [comment]
Awesome, thanks!
