### ISSUE TITLE
amazon: accessKeyID is required

### ISSUE THREAD

**Issue by pwecker** [chilts/awssum#21]
The s3 example you've given is getting me this error.

**Comment by chilts** [comment]
Which example? What's the error?

**Comment by pwecker** [comment]
Sorry, the example in Readme.md. My amazon credentials are correct but I get this:

$ node server.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
amazon: accessKeyID is required

**Comment by chilts** [comment]
Can you paste the code you have in your constructor. Please note that the README is referring to v0.5.1 which is on NPM. If you have v0.4.0 that's why it's not working. Have a look in your examples/amazon/s3/ directory for some examples that will work with your version.

Many thanks.

**Comment by chilts** [comment]
But if you can, please upgrade to v0.5.1. :) Thanks.

**Comment by pwecker** [comment]
ugh of course; the examples folder. sorry, thanks for the fast response!!!

**Comment by chilts** [comment]
No worries and thanks for closing. :)
