### ISSUE TITLE
S3 Signature Creation does not add necessary params in signature computation

### ISSUE THREAD

**Issue by frooble** [chilts/awssum#23]
The S3 [GetObject](http://docs.amazonwebservices.com/AmazonS3/latest/API/RESTObjectGET.html) method seems to need certain optional parameters to be included in the signature calculation (e.g. parameters like `response-content-type`, and `response-content-encoding`). However the S3.prototype.strToSign method filters out parameters

``` javascript
if ( options.params.length ) {
        strToSign += _(options.params)
            .chain()
            // here  is the filtering
            .filter(function(pair) { return validSubresource[pair.name]; } )
            .sortBy(function(pair) { return pair.name; } )
            .map(function(pair){
                return _.isUndefined(pair.value) ? 
                         pair.name : pair.name + '=' + pair.value;
            })
            .reduce(function(memo, pairStr) {
                return memo === '' ? '?' + pairStr : memo + '&' + pairStr;
            }, '')
            .value()
        ;
    }
```

where `validSubResource` list is 

``` javascript
var validSubresource = {
    acl            : true,
    'delete'       : true,
    lifecycle      : true,
    location       : true,
    logging        : true,
    notification   : true,
    partNumber     : true,
    policy         : true,
    requestPayment : true,
    torrent        : true,
    uploadId       : true,
    uploads        : true,
    versionId      : true,
    versioning     : true,
    versions       : true,
    website        : true,
};
```

Adding 

``` javascript
'response-content-encoding' : true,
```

when using this parameter with an s3 GetObject request will eliminate the `SignatureDoesNotMatch` error that occurs otherwise.

There may be other s3 methods for which other parameters need to be included in this list

**Comment by chilts** [comment]
Hiya,

Thanks for this... man, sometimes I hate the AWS docs (sometimes it's ok). Anyway, I've done the fix but slightly different to what you suggested. Instead of looking for the 'sub-resources' it now just uses any of the args which are params to the query. This is slightly more correct than your suggestion and will be correct for any and all other params such as the ones you are using in GetObject.

Is it possible for you to get the master branch from GitHub and re-try your requests?

Many thanks,
Andy

**Comment by chilts** [comment]
Ok, you were right. I should have done what you said the other day! :) Ah well, I'm happy it's now fixed (again (properly)).

So I borked v0.6.0 so if you're using that, please upgrade to the newly minted v0.6.1.

And thanks again for pointing this out. You'll be pleased to know that I now have some integration tests that I'll run on each release which should make AwsSum releases an even higher quality.
