### ISSUE TITLE
AWS https request needs to handle 'error' events

### ISSUE THREAD

**Issue by frooble** [chilts/awssum#24]
The `request` method in AwsSum creates a https but `req.on('error', ...` is not used so request errors will cause a crash.
Error should propagate to invoker.

``` javascript
AwsSum.prototype.request = function(options, callback) {
    var self = this;

   /** .................. content deleted for brevity ...................*/
    // do the request
    var req = https.request( reqOptions, function(res) {
```

**Comment by chilts** [comment]
Please upgrade to the latest release or use the master branch from GitHub:
- https://github.com/appsattic/node-awssum/blob/master/lib/awssum.js#L806

Many thanks :)
Andy
