### ISSUE TITLE
Setting ResponseContentType Causes Signature Mis-Match with AWS S3

### ISSUE THREAD

**Issue by dnndev** [chilts/awssum#27]
When working with the Amazon S3 module, when calling s3.GetObject with the ResponseContent type set (I set it to "text/plain"), S3 returns "SignatureDoesNotMatch". When I removed ResponseContent, the error disappeared. After some research, it appears S3 is very picky about case in header names. It requires "Content-Type", not "content-type" See this thread:

https://forums.aws.amazon.com/thread.jspa?threadID=94986

Best,
Kelly

**Comment by chilts** [comment]
Hi Kelly,

Thanks for your note and digging into the issue. :) As you know, I'm
away at the moment, but I'll try and find time to fix and re-release
this as soon as I can. :)

One thing I am noticing is that S3 does seem to be picky/fickle
(depends on your perspective) so bug reports like this are critical to
getting it to work 100%. :) Thanks again and much appreciated.

Cheers,
Andy

## 

contact: Andrew Chilton
website: http://www.chilts.org/blog/

**Comment by chilts** [comment]
Hi Kelly,

Am back from holiday. Hope you've been keeping well.

Can you let me know which version of AwsSum and which version of node you are using?

I've just looked at a fair bit of stuff around this and also see that I have an integration test related to the ResponseContentType param. I've also just added a couple more tests to make sure it works fine now and keeps working - https://github.com/appsattic/node-awssum/commit/bc163fab781f2f43932a85a156f542cfda3a2d1b

Can you get a copy of master and let me know if it still fails for you or if it now works?

Many thanks,
Andy

**Comment by dnndev** [comment]
It was the most current version before you left for holiday. Looking at package.json, it's 0.5.1.

I'll get a copy as soon as I'm able. Will try to test this weekend.

FYI, I'm still interested in that other project.

Cheers,
Kelly

**Comment by chilts** [comment]
Hi Kelly,

AwsSum has been on the 0.6.x series for about 7 weeks now. :)

http://search.npmjs.org/#/awssum

Will wait to hear from you at the weekend and will leave this request open until I hear back. I think it's fixed in the 0.6.x series, now up to 0.6.2.

Cheers,
Andy

**Comment by dnndev** [comment]
That may be the problem. Everytime I run npm install, I get version 5.1.

**Comment by dnndev** [comment]
DOH. I just realized I was restricting the AWS vsn via my package.json. I'll test and let you know.

**Comment by chilts** [comment]
I suspect whatever this problem is, it is now fixed in the latest version of AwsSum. Please re-open if it still persists. :)

Thanks.
