### ISSUE TITLE
Add support for DynamoDB

### ISSUE THREAD

**Issue by mhart** [chilts/awssum#3]
I'm sure you've got this on the cards already, but it doesn't hurt to have an issue here to keep track of it :-)

**Comment by chilts** [comment]
Hi mhart, :)

No problem about putting it in here!

I'm in the process of doing DynamoDB now though I've just been away for a long weekend. I hope to have the start of a working version by the weekend and it completed sometime next week (by approx. 2012-02-10).

Cheers,
Andy

**Comment by chilts** [comment]
Well, it took me a bit longer than I anticipated (getting married and going on honeymoon in the middle are good delay reasons). :) It's now in master and will be released onto NPM shortly as version v0.4.0.

**Comment by mhart** [comment]
This is great! But I can't see it in master - are you sure it's been merged?

**Comment by chilts** [comment]
Oh my! Schoolboy error. :(

I've merged the amazon-dynamodb branch and released v0.4.1! :)

Thanks for the heads up, how embarassing.

**Comment by chilts** [comment]
Hi Michael,

Just wanted to catch up and see if you were using DynamoDB with AwsSum? Am trying to find testimonials for my new docs site: http://awssum.appsattic.com/ and wondered if you might be able to share any thoughts or stories.

Cheers,
Andy
