### ISSUE TITLE
x-amz-meta-cache-control header set to S3 object instead of Cache-Control

### ISSUE THREAD

**Issue by krootee** [chilts/awssum#34]
If you try to upload file to S3 using PutObject and specify MetaTag 'Cache-Control' then created object will have tag 'x-amz-meta-cache-control' instead of it.

You could replicate this behavior if you use example (https://github.com/appsattic/node-awssum/blob/master/examples/amazon/s3/put-object.js) and add to MetaData 'Cache-Control': 'max-age=1209600'.

Per AWS documentation this should happen if you incorrectly sends data to AWS.

**Comment by chilts** [comment]
I think by adding your Cache-Control to the MetaTag info, you're doing it wrong. There is a CacheControl option which you can specify.

e.g.

```
var body = "Hello, World!\n";

var optionsWithCacheControl = {
    BucketName    : 'pie-18',
    ObjectName    : 'test-cache.txt',
    ContentLength : Buffer.byteLength(body),
    Body          : body,
    CacheControl  : 'max-age=3600'
};

s3.PutObject(optionsWithCacheControl, function(err, data) {
    console.log("\nputting an object with cache-control to pie-18 - expecting success");
    inspect(err, 'Error');
    inspect(data, 'Data');
});
```

Please try that and let me know how it goes.

**Comment by krootee** [comment]
Thanks - got it working now.

**Comment by chilts** [comment]
No worries. Thanks for raising it. :)
