### ISSUE TITLE
Route53 doesn't actually need a region option.

### ISSUE THREAD

**Issue by danfuzz** [chilts/awssum#35]
I noticed that the `Route53` constructor requires a `region` option. Without it, the constructor fails with the message `amazon: region is required`. The odd thing is that the underlying Route53 service doesn't actually have any region dependencies; there's only one URL to access Route53 from anywhere.

Is it possible to remove the requirement the region option in this case?

Thanks for your consideration, and thanks for putting together an awesome/awssum module.

**Comment by chilts** [comment]
Hi Dan,

Thanks for adding this issue. I know it's something other people didn't like either though it did (originally) make sense to me as I added a lot of Amazon services in parallel. Anyway, I think you guys are right so have changed it in the following services:
- Route53
- SES
- CloudFront
- STS

I think that's most of them.

In the background there is still an idea of region but it is a default in the constructor. The user doesn't see this at all and can skip passing the region in. :)

Again, many thanks,
Andy

**Comment by chilts** [comment]
Ok, typing 'Fixes 35' into the commit message doesn't close the issues. The commit is:
- https://github.com/appsattic/node-awssum/commit/e79ad485be9cd820cf627207b5927285516d1f7a

:)

**Comment by danfuzz** [comment]
Much obliged!

**Comment by chilts** [comment]
I'll be doing a v0.7.0 release later today, so you got your stuff in at the right time. :)
