### ISSUE TITLE
Route53: XML wrong for multiple-value A records

### ISSUE THREAD

**Issue by danfuzz** [chilts/awssum#36]
I tried creating a multiple-value A record, using a request argument to `Route53.ChangeResourceRecordSets()` that looks like this:

``` javascript
var request = {
  HostedZoneId: "<my id>",
  Comment: "Generated programatically.",
  Changes: [ {
    Action: "CREATE",
    Name: "blort.example.com.",
    Type: "A",
    Ttl: 300,
    ResourceRecords: [ "10.0.0.1", "10.0.0.2" ]
  } ]
};
```

This resulted in getting an error back from Amazon stating:

```
Invalid XML ; cvc-complex-type.2.4.d: Invalid content was found
starting with element 'Value'. No child element is expected at this point.
```

I flipped on the debug flag in awssum and saw that the XML generated for this request looked like this:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<ChangeResourceRecordSetsRequest xmlns="https://route53.amazonaws.com/doc/2011-05-05/">
<ChangeBatch>
  <Changes>
    <Change>
      <Action>CREATE</Action>
      <ResourceRecordSet>
        <Name>blort.example.com.</Name>
        <Type>A</Type>
        <TTL>300</TTL>
        <ResourceRecords>
          <ResourceRecord>
            <Value>10.0.0.1</Value> <!-- problem here! -->
            <Value>10.0.0.2</Value>
          </ResourceRecord>
        </ResourceRecords>
      </ResourceRecordSet>
    </Change>
  </Changes>
</ChangeBatch>
</ChangeResourceRecordSetsRequest>
```

It looks like the problem is that each of the `<Value>` elements should be in its own `<ResourceRecord>` instead of all being bunched together.

Note: I'm using awssum v0.6.1.

**Comment by chilts** [comment]
I think this is now fixed because I pulled request 37. That right? (ie. I have commit 0049f8a but not commits 28231b2 or 4d51c26).

Dan, it's lovely to get pull requests, so thank you. :) You're a star.

**Comment by danfuzz** [comment]
Yes, just the one commit should do it. The other two commits were the result of me trying (but failing) to squash an earlier version together with the final fix. I then just made a fresh branch, which is what became PR #37.

Thanks for taking the PR, and especially thank you for all the hard work that went into the module in the first place.

**Comment by chilts** [comment]
A pleasure. :)
