### ISSUE TITLE
S3 Signature matching issue 

### ISSUE THREAD

**Issue by samccone** [chilts/awssum#38]
I am downloading an image and then uploading it to S3 but I keep getting       

 "Code": "SignatureDoesNotMatch",
            "Message": "The request signature we calculated does not match the signature you provided. Check your key and signing method.",

I was wondering if you had any insight.

Thanks
## Downloads the images and then sends them to S3

downloadImage = (src, cb) ->
  request.get
    url: src
    encoding: 'binary'
  , (err, response, body) ->
      if err
        cb "error downloading image " + JSON.stringify(err, null, 4)
      else
        uploadToS3 body, (new Date).getTime()+"."+response.headers["content-type"].split('/')[1], src, (error, data) ->
          if error
            cb error
          else
            cb null, data
## Uploads Image To S3

uploadToS3 = (data, filename, originalName, cb) ->
  s3 = new S3
              accessKeyId: s3Keys.access_key_id
              secretAccessKey: s3Keys.secret_access_key
              region: amazon.US_EAST_1

  buf = new Buffer data, 'binary'
  s3.PutObject
    BucketName: s3.bucket
    ObjectName: filename
    ContentLength: buf.length
    Body: buf
  , (err, data) ->
    if err
      cb "Problem Uploading to S3 " + JSON.stringify(err, null, 4)
    else
      data.newFileName = filename
      data.originalName = originalName
      cb null, data

**Comment by samccone** [comment]
this is also in the error message 

looks like.. something is undefined for some reason

"StringToSign": "PUT\n\n\nSun, 22 Jul 2012 17:21:40 UTC\n/undefined/downloaded%2F1342977700891",

**Comment by chilts** [comment]
Which version of AwsSum are you using? If it's not at least v0.6.0 then please upgrade and try again.

Which version of node are you 

Cheers,
Andy

**Comment by samccone** [comment]
hi @chilts I am using   "version": "0.7.0"

let me know if I can provide any more debugging info 

## 

node v0.6.19

**Comment by chilts** [comment]
Thanks Sam. I'll look into it later today. :)

By the way, what is this line:

BucketName: s3.bucket

Looks like you are trying to use 'bucket' from the (AwsSum) s3 instance. That property doesn't exist. I think you might need something else in there. Can you try hardcoding:

BucketName: 'you-bucket-name-whatever-it-is'

Thanks.

**Comment by samccone** [comment]
ahh it is a value in a keys file i have set.. but i will hardcode and see what happens

**Comment by samccone** [comment]
im an idiot you win you were right s3.bucket was the issue 

the strange thing was that this worked at some point :)

**Comment by chilts** [comment]
Ohh, was just about to close. Thanks for doing it for me. :)

I really should check that some things like that are no 'undefined'. But, that might have repercussions elsewhere. Let me think about it a while.
