### ISSUE TITLE
Route53 wants query parameter names to start with a lower case letter.

### ISSUE THREAD

**Issue by danfuzz** [chilts/awssum#39]
It's great for consistency that the awssum API always uses upper-cased names. Unfortunately, though, it looks like it currently fails to lower-case these names when it comes time to put together a Route53 request with query parameters. That is, if you say something like this:

``` javascript
var request = {
  HostedZoneId: "my-id",
  Name: "some.example.com",
  Type: "CNAME"
};

r53.ListResourceRecordSets(request, onResult);
```

then awssum parses and recognizes the `Name` and `Type`, but it includes those strings per se as query parameters, instead of the `name` and `type` that the Route53 API actually expects.

I confirmed this by turning on `debug` in `lib/awssum.js` and noting the URL it used:

```
awssum.js:request(): reqOptions =  { method: 'GET',
  host: 'route53.amazonaws.com',
  path: '/2011-05-05/hostedzone/my-zone-id/rrset?Name=my-name.example.com&Type=CNAME',
```

**Comment by chilts** [comment]
Hi Dan,

Thanks for the heads up. I've added some examples to the examples/ dir too which makes sure that the fields that are parameters to the request (rather than in the XML) are all lowercased. :)

Cheers,
Andy

**Comment by danfuzz** [comment]
Sweet. You rock.
