### ISSUE TITLE
one parameter in swf.RegisterDomain is incorrect

### ISSUE THREAD

**Issue by pierreg256** [chilts/awssum#40]
Hey :-)

Just beginning a development with the swf part of your framework and just stumbled upon a typo in the lib/amazon/swf-config.js
In the exports, the RegisterDomain is written like this:

``` javascript
    RegisterDomain : {
        // request
        defaults : {
            'Target' : 'RegisterDomain',
        },
        args : {
            'Target' : {
                'required' : true,
                'type'     : 'special',
            },
            'Description' : {
                'name'     : 'description',
                'required' : false,
                'type'     : 'json',
            },
            'Domain' : {
                'name'     : 'domain',
                'required' : true,
                'type'     : 'json',
            },
            'WorkflowExecutionRetentionPeriodInDays' : {
                'name'     : 'workflowExecutionRetentionPeriodInDays',
                'required' : true,
                'type'     : 'json',
            },
        },
        body : bodyJson,
    }
```

But according to the aws doc, the "Domain" arg should have a name of _"name"_ instead of _"domain"_. I tried to change it in my local copy and it works! (HTTP 400 otherwise)

**Comment by chilts** [comment]
Hi Pierre,

Wow, that was pretty quick! Thanks for the bug report.

I've changed the line which said 'Domain' with the name of 'domain', to be exactly like the docs, so it's now 'Name' with a name of 'name' (just to confuse things).

Want me to release v0.7.1 with your patch, or are you happy using this master branch for the moment? I'll re-release in a day or so in case I get any more early bug reports.

Cheers,
Andy

P.S. I'd love if you could let me know how you go using the library, and also any feedback so I know where to put my energies. :)

**Comment by pierreg256** [comment]
Hi Andy,
Absolutely OK to work with this master branch for now :-)
I'll be working on the swf part of your library for the next weeks/months and would be more than happy to provide feedback on that part!

Cheers,
Pierre.

**Comment by chilts** [comment]
Excellent. Thanks. I hope it goes well! :)

Cheers,
Andy
