### ISSUE TITLE
When the server response is empty, swf crashes

### ISSUE THREAD

**Issue by pierreg256** [chilts/awssum#43]
Andy,
sorry to bother with another issue... (I know i can be a real pain...)

Using SimpleWorkflowService.RespondDecisionTaskCompleted I understood that AWS was giving no content, even though the status code was 200 (204 would have been better). As a result, the JSON.parse you do on the body crashes...

Is there a way to specify that the bodyparse should be 'none' instead of 'json' directly in the swf-config.js (or even in the operation call params)?

cheers,
Pierre.

**Comment by chilts** [comment]
Thanks Pierre. You're a star.

I've reviewed all of the other operations and made sure each operation now expects nothing to be returned. You're right, a 204 from SWF would have been better. It's also strange that they reply with 'Content-Type' 'application/json'.

Hopefully I've fixed everything up now. :)

Cheers,
Andy
