### ISSUE TITLE
Filters seem to be ignored (EC2)

### ISSUE THREAD

**Issue by mikey-** [chilts/awssum#45]
Hi,

If I use something like this

<pre>
ec2.DescribeTags({FilterName: ['resource-type'], FilterValue:['instance']},
        function(err, data) {
            if(err){
                console.log('Error: ' + JSON.stringify(err));
            }else{
                console.log('Data: ' + JSON.stringify(data));
            }
        });
</pre>

It just describes all resources, no matter the type. 

I couldnt find any documentation about how to use DescribeTags on here :S

**Comment by chilts** [comment]
Hi Mikey, Thanks for getting in touch. :)

Can you try the following for me please. I think that should be what you need:

ec2.DescribeTags({ Filter : { Name : 'resource-type', Type : 'instance' } },
        function(err, data) {
            if(err){
                console.log('Error: ' + JSON.stringify(err));
            }else{
                console.log('Data: ' + JSON.stringify(data));
            }
        });

I'm currently in the process of writing more extensive docs on a separate site, with hopefully lots of examples, though I'm not quite ready yet. :)

Cheers,
Andy

**Comment by chilts** [comment]
Hmm, I got that wrong:

```
ec2.DescribeTags({
    Filter : [
        { Name : 'resource-type', Type : 'instance' }
    ]
}, function(err, data) {
    // ...
});
```

Cheers,
Andy

**Comment by mikey-** [comment]
Hey no worries ^_^

Thanks for the quick reply!

Here's what I have now:

<pre>
ec2.DescribeTags({
    Filter : [
        { Name : 'resource-type', Type : 'instance' }
    ]
}, function(err, data) {
    if(err){
        console.log('Error: ' + JSON.stringify(err));
    }else{
    console.log('Data: ' + JSON.stringify(data));
    }
});
</pre>


and I get the following error message back:

<pre>
Error: {"StatusCode":400,"Headers":{"transfer-encoding":"chunked","date":"Tue, 07 Aug 2012 06:16:46 GMT","cneonction":"close","server":"AmazonEC2"},"Body":{"Response":{"Errors":{"Error":{"Code":"UnknownParameter","Message":"The parameter undefined is not recognized"}},"RequestID":"7eb46f30-f786-4d53-b81e-e300244ff075"}}}
</pre>

**Comment by mikey-** [comment]
I also get the same error message when trying it the first way ( I know you said it was wrong but I'm clutching at straws haha)

**Comment by chilts** [comment]
Hi Mikey,

I've put an example script into the repository. Can you get it for me and run it on your machine:
- https://github.com/appsattic/node-awssum/blob/master/examples/amazon/ec2/describe-tags.js

Remember to set the environment variables ACCESS_KEY_ID and SECRET_ACCESS_KEY.

So something like:

```
$ export ACCESS_KEY_ID=???
$ export SECRET_ACCESS_KEY=???
$ wget https://raw.github.com/appsattic/node-awssum/master/examples/amazon/ec2/describe-tags.js
$ node describe-tags.js
```

Many thanks for pursuing this. I suspect that it may be something at your end since I can run the above script fine. :)

Cheers,
Andy

**Comment by chilts** [comment]
Hey Mikey,

Scap everything I just said ... sorry. :)

I'm presuming you're using v0.7.0. There is a bug in that which has been fixed in trunk! Would it be possibly to clone this repo and try again. I'm _almost_ due for a new release, but it's a day or two off before I put it on NPM so I think trying the master branch is going to fix your problem.

Cheers,
Andy

**Comment by mikey-** [comment]
oh :) haha no worries :) 

Well I installed this from npm so what ever version is in there is the one that I have. Is there a way I can check? 

Also, is there anymore info on this bug?  Just for my own knowledge is all. I'm not impatient so I'm happy to wait until the nnext release ^_^

**Comment by chilts** [comment]
Hi Mikey,

Not sure what more info you need here?

Anyway, to check which version you have you can take a look in the package.json file for the version string. If you're from NPM then yes, you'll be on v0.7.0.

Closing this until I hear otherwise (using master, or the next version).

Cheers,
Andy

**Comment by mikey-** [comment]
I'll let you know how it goes. Thanks for all the help! This is an awssum :P lib you got going here ^_^

**Comment by chilts** [comment]
Hey Mikey,

Many thanks for your compliments. :) _blushes_

Cheers,
Andy
