### ISSUE TITLE
Support for Eucalyptus 

### ISSUE THREAD

**Issue by jeevanullas** [chilts/awssum#47]
Hi all,

It would be great if support can be added for Eucalyptus (http://www.eucalyptus.com) as well. Let us know what further information is required to proceed.

Eucalyptus has high fidelity with AWS API and currently implements EC2 (Eucalyptus) , S3 (Walrus) and IAM (EIAM) in the latest release 3.1

Basically figuring out how to call the Eucalyptus and Walrus endpoint from within awssum would help in getting the ball rolling and later we can just use the AWS calls (as far as my experience says).

Thanks again!
Deependra

**Comment by kosmasgiannis** [comment]
+1

**Comment by chilts** [comment]
AwsSum is now deprecated in favour of the offical aws-sdk from Amazon. Thanks for opening this originally.
