### ISSUE TITLE
S3 PutObject example not working

### ISSUE THREAD

**Issue by standingwave** [chilts/awssum#5]
Just trying the library out and I can't get this example to work.  The first part of the example works in that I'm able to get a list of my S3 buckets.  When I try to upload a test file I get this error response:

``` javascript
{ Body: '',
  Headers: 
   { 'x-amz-request-id': 'C3A64A352D1040DA',
     'x-amz-id-2': 'quYON1SumP6CVmFZAteJQbudyUKzJ9CbaTzw977cftIvYarUECXRz67GzhAPN7fT',
     'content-type': 'application/xml',
     'transfer-encoding': 'chunked',
     date: 'Thu, 01 Mar 2012 20:06:33 GMT',
     nncoection: 'close',
     server: 'AmazonS3' },
  StatusCode: 301,
  Code: 'AwsSum-IncorrectStatusCode',
  Message: 'Status code was not expected' }
```

I'm not sure why AWS would be returning a 301 but clearly it's not what awssum is expecting.  Has the S3 api or endpoint changed perhaps?  Any insight would be greatly appreciated.

**Comment by chilts** [comment]
Hiya,

Thanks for your report.

From what I can see, a 301 means that the location of the URL has changed, but I can't see a 'Location' header in the response you pasted (so I'm slightly confused). I'll take a look at the code later on and just check I'm doing the right thing with the returned headers.

Would it be possible for you to paste your request, i.e. the bit inside the s3.PutObject( ... ) call?

Many thanks,
Andy

**Comment by chilts** [comment]
http://docs.amazonwebservices.com/AmazonS3/latest/dev/Redirects.html

There is definitely some stuff here about the 301 and a redirection, but I'm still not sure why it didn't appear as a Location header in the response.

**Comment by standingwave** [comment]
Thanks for the quick response!  The request is pretty much exactly out of the example, just with one of my bucket names:

``` javascript
s3.PutObject({
        BucketName : 'my-test-bucket',
        ObjectName : 'test.txt',
        ContentLength : '14',
        Body          : "Hello, World!\n",
    }, function(err, data) {
        console.log(err);
        console.log(data);
    });
```

Oh, I also added the console.log(err), the results of which I included in my initial post.  The data response comes back null.

**Comment by chilts** [comment]
Hiya,

Great thanks. :)

Ok, I'm not sure what to do next but I'll have a read around and a think. Could you do me a favour and try doing it again in half a day, then tomorrow and again the day after and paste the results. I want to figure out if it is an intermittent error (ie. your bucket is redirecting you to a new server) or permanent with you. I just tried it again from here and it was fine.

Many thanks for your help.

Cheers,
Andy

**Comment by standingwave** [comment]
Weird that it's working for you.  I tried a couple of different buckets on
the same account and got the same redirect issue.  Maybe it's a region
problem?  Is it working for you in US-West?

Seems like it would be reasonable for awssum to follow a 301 since it's a
perm redirect.

On Thu, Mar 1, 2012 at 12:43 PM, Andrew Chilton <
reply@reply.github.com

> wrote:
> 
> Hiya,
> 
> Great thanks. :)
> 
> Ok, I'm not sure what to do next but I'll have a read around and a think.
> Could you do me a favour and try doing it again in half a day, then
> tomorrow and again the day after and paste the results. I want to figure
> out if it is an intermittent error (ie. your bucket is redirecting you to a
> new server) or permanent with you. I just tried it again from here and it
> was fine.
> 
> Many thanks for your help.
> 
> Cheers,
> Andy
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/appsattic/node-awssum/issues/5#issuecomment-4269799

## 

"I woke the same, as any other day, except a voice was in my head."

**Comment by standingwave** [comment]
I just tried this again and I'm still getting the redirection message.  Any insight or should I just bail and try a different S3 library?

**Comment by chilts** [comment]
Hiya,

On 9 March 2012 12:32, standingwave
reply@reply.github.com
wrote:

> I just tried this again and I'm still getting the redirection message.  Any insight or should I just bail and try a different S3 library?

Sorry I haven't managed to figure this out yet. I'm going to be crazy
over the next few weeks (major life change :) so unless you can wait
until the start of April, then yeah, go for another library. I wish I
didn't have to say that but it's probably best if you need to crack on
with whatever you need it for. :)

Cheers and thanks for your patience,
Andy

## 

contact: Andrew Chilton
website: http://www.chilts.org/blog/

**Comment by chilts** [comment]
Hiya,

With the latest change on master, the headers are now being populated into the response. Would it be possible for you to re-do your request and paste here the response (including the Location header)?

Many thanks,
Andy

P.S. Note, the fix is only on master, not yet in a release on npm. :)

**Comment by standingwave** [comment]
Tries this again and the example worked just fine for me, although I've already switched my app over to use knox so I haven't used the library in the field at all.

**Comment by chilts** [comment]
Hi standingwave,

Thanks for trying it again. I think the redirect happens when a bucket is relocated to a different availability zone or even a different region, so I still don't have any code to work with that. I presume your bucket is now sitting happily somewhere and no longer needs a redirect. :)

Many thanks for trying it out again and for all your help and patience. :)

Cheers,
Andy

**Comment by chilts** [comment]
Closing this issue since it may have been a temporary thing. There may be a need to listen to S3 redirects but I'll open a specific issue for that in the future. :)
