### ISSUE TITLE
Increasing http.Agent.maxSockets?

### ISSUE THREAD

**Issue by joachimkainz** [chilts/awssum#51]
Is there any clean way to increase the value of http.Agent.maxSockets for the https clients created by awssum?

**Comment by chilts** [comment]
Hiya Joachim,

AwsSum doesn't provide a nice way to do it yet, but this doesn't mean it can't. The real question however is whether it should.

Changing it would change it for the whole application, so I'd probably err on the side that the user should do it themselves. Let me know if I've got this wrong and I'd be happy to listen to suggestions.

Certainly there is one thing I can do, and that is to document it explicitly in the README and making sure that if people do or don't set it, they are doing it because they know what they're doing, rather than because they don't know about it.

How does that sound?

Cheers,
Andy

**Comment by joachimkainz** [comment]
Andy,

It seems to me that one can explicitly pass a http.Agent object as part of
http.request()/http.post()/http.get().

agent: Controls
Agenthttp://nodejs.org/api/http.html#http_class_http_agent behavior.
When an Agent is used request will default to Connection: keep-alive.
Possible values:
- undefined (default): use global
  Agenthttp://nodejs.org/api/http.html#http_http_globalagent for
  this host and port.
- Agent object: explicitly use the passed in Agent.
- false: opts out of connection pooling with an Agent, defaults request
  to Connection: close.

That is what I was hoping we can use.

I would be glad to fork & do the work, if you direct me how you would like
to have this one.

Best regards,

Joachim

**Comment by chilts** [comment]
Hi Joachim,

Ah, ok, it's becoming clearer. This is also related to Issue #18 (I hope GitHub marks that up to a link).

In which case, I suspect the best way to do it would be to pass your own Agent into the constructor. For example:

var s3 = new S3({
    'accessKeyId' : accessKeyId,
    'secretAccessKey' : secretAccessKey,
    'region' : amazon.US_EAST_1,
    'agent' : myAgent,
});

I think when @frooble opened that issue, I wasn't sure what he meant and also I think his suggested solution was in the wrong place. I think by doing it the above way, it's the proper way to do it. :)

How does that solution sound to you? I'm guessing that this means you'll create your own agent which has maxSockets set and pass that as the agent to be used. Sounds good to me.

Many thanks,
Andy

**Comment by joachimkainz** [comment]
Yup, my issue is a dup of #18.

**Comment by chilts** [comment]
Hi Joachim,

I've added support for specififying your agent when you create the client. See this here for an example:
- https://github.com/appsattic/node-awssum/blob/master/test/integration/agent.js

You can also specify false to opt-out of the global agent, or specify your own. If you don't specify anything, the global one will be used as it is currently. :)

Thanks for opening this request.

Cheers,
Andy

**Comment by joachimkainz** [comment]
Andrew,

Awesome! Thank you very much. Makes a real difference for my
jolira-replicator/s3-store performance.

FYI: Your product is slated to be used in production at a large US men's
clothing store in the next few weeks. :)

Best regards,

Joachim

---

(415) 323-5672 gtalk/xmpp: jfk@jolira.com twitter: 4jolira skype:
joachim_kainz

**Comment by chilts** [comment]
Hi Joachim,

That's brilliant! Thanks.

When you guys release, would you mind if I got a testimonial off you for the new docs site. It's not yet anywhere near complete, but here's a sneak preview:
- http://awssum.appsattic.com/

It'd be great if I could show people what AwsSum is being used for. :)

Many thanks for your continued support.

Cheers,
Andy
