### ISSUE TITLE
Controlling context inside callback

### ISSUE THREAD

**Issue by mikey-** [chilts/awssum#55]
Hi Again!

Once again, this is a really cool lib and it's v powerful so thanks for all your hard work ^_^ 

I'm not sure if this is a stupid question but I couldnt find an answer in the docs

Is there a way to control the context inside the callback function of the request?

take this code for example:

<pre>
var awssum = require('awssum');
var amazon = awssum.load('amazon/amazon');
var S3 = awssum.load('amazon/s3').S3;

var s3 = new S3({
    'accessKeyId' : accessKeyId,
    'secretAccessKey' : secretAccessKey,
    'region' : amazon.US_EAST_1
});

s3.ListBuckets(function(err, data) {
    if (err) {
        // something went wrong with the request
        console.log(err);
        return;
    }

    // request was fine
    this.response = data;
    console.log(data);
});
</pre>

forget that I haven't defined this.response anywhere; my question is, is there a way that I can control what 'this' is? 

Thanks,
Mikey

**Comment by chilts** [comment]
Hiya,

Interesting question and one I've been thinking about recently too. How does this look?

```
var awssum = require('awssum');
var amazon = awssum.load('amazon/amazon');
var S3 = awssum.load('amazon/s3').S3;

var person = {
    uuid : '47836f34-8873-40ee-aa84-f287b104c6cf',
    processListBuckets : function(err, data) {
        console.log(this.uuid + ' is processing ListBuckets Result');
        console.log(err);
        console.log(data);
    },
};

console.log('Called without binding');
person.processListBuckets('a', 'b');

person.uid = 'ba37e36f-ba19-4191-a238-a40d31294e17';

// do a ListObjects

var env             = process.env;
var accessKeyId     = env.ACCESS_KEY_ID;
var secretAccessKey = env.SECRET_ACCESS_KEY;
var awsAccountId    = env.AWS_ACCOUNT_ID;

var s3 = new S3({
    'accessKeyId'     : accessKeyId,
    'secretAccessKey' : secretAccessKey,
    'region'          : amazon.US_EAST_1
});

console.log('Called WITH binding');
s3.ListBuckets(person.processListBuckets.bind(person));
```

.bind() is probably what you want. I'm not entirely sure but I think it should work. Let me know how it goes since I'd love to hear what you're doing with it? :)

Cheers,
Andy

**Comment by mikey-** [comment]
oh cool! all right I'll give it a go. I'll let you know how it goes.

Basically, I'm trying to create an 'environment launcher' for work to launch weekly test environments. Its basically an object with a bunch of functions to fully automate this process.

 After it gets all the info it has to (mainly the ami and elastic ip to use), it passes it into the cloudformation template which will launch the environment.

 some of the things it does
- It automatically finds the previous weekly testing ec2 instance, create an AMI from it
- It will find a free elastic IP (one that isnt associated with any e2c instance) and then checks route53 for any existing A records that contain the IP (just for a bit of clean up)  

these functions set values of properties in the main object, which is why I'd like to use 'this'

**Comment by chilts** [comment]
Hey Mikey,

That sounds cool! If the project is open source, let me know since I'd love to see it. If it isn't no worries, but good to know what you're doing.

I'm going to close this issue for now, but feel free to re-open if you need any more help or think that we should do something a different way.

Cheers,
Andy

**Comment by mikey-** [comment]
ummmmm yeah it shouldn't be a problem but at the moment it has some access keys and secret keys which are baked into the code so I need to fix that before I open it up ha. Then there are a few other things I'd like to clean up too, I'm new to  I'll let you know when I get it going though! 

aaaarrrrggggghhh you're awesome! using bind totally worked. Thanks again.
