### ISSUE TITLE
Cant set the region with rds object

### ISSUE THREAD

**Issue by mikey-** [chilts/awssum#58]
Hi Again,

It appears that no matter what you try set the region to in an rds object, it will always go back to us-east-1

This is a problem because I'm working on instances in us-west-1 and ap-southeast-1 and maybe others :(

I can see in /lib/amazon/rds.js that the region is set to the default us-east-1 and it is commented with:
// we only have one region for this service, so default it here

In the case of rds this isn't correct! it may have been at one time or another but it defs isn't any more

^_^

Thanks

Mikey

**Comment by chilts** [comment]
Hi Mikey,

I'm really appreciative of your efforts in AwsSum, seriously. Without pioneers like you, things wouldn't be as good.

Sorry about that one, I think I was over-zealous when fixing a different bugs a month or so ago. I had all the regions specified in RDS, I just wasn't taking note of them. :)

All fixed now. Have fun!

Cheers,
Andy

**Comment by mikey-** [comment]
Hey! ha no worries :) glad to help where ever I can! 

No worries, yeah I saw that you specified all the regions :P I just tried it out and its all good now! 

Thanks again ^_^

**Comment by chilts** [comment]
Great! :)

By the way, you're probably one of the first people to use RDS, so don't hesitate to shout if you need help or find something weird. I'll try and get through any issues as fast as I can.

Thanks again,
Andy

**Comment by mikey-** [comment]
Thanks! 

oh really? its really really handy. The tricky part with rds is that everything takes so long. Like, the requests are done really quickly but then you have to wait until the instance is actually created, backed up and is available. I managed to handle that okay (I think haha). 

I seem to be having a problem with running ModifyDBInstance though. It keeps spitting some error (Next time I get it, after I check whether its a problem with aws or awssum, I'll create an issue :D )

**Comment by chilts** [comment]
Yeah, that'd be great. Whatever you find, create a separate issue and then it's easier to keep track of. :)

Cheers and good luck with wrangling RDS to whatever you need! Yeah, I hate it when you have to keep checking the status of something before you can do other stuff. :)

Cheers,
Andy

**Comment by chilts** [comment]
Have just reviewed ModifyDBInstance and it's looks ok, apart from one extraneous parameter I had in there. Maybe that was the problem (I have Engine as well as EngineVersion, but Engine doesn't exist).
- https://github.com/appsattic/node-awssum/commit/c688f8a598673408f1de18e5bbf43984306b7a3e

Cheers,
Andy

**Comment by mikey-** [comment]
Yeah, I was just finishing off writing an issue. As you said everything appears to be fine except for the Engine parameter. Should I still bother posting the issue? haha

Mikey

**Comment by mikey-** [comment]
also, THANK YOU ^_^
