### ISSUE TITLE
SNS examples don't work

### ISSUE THREAD

**Issue by katowulf** [chilts/awssum#6]
I've tried the example [here](https://github.com/appsattic/node-awssum/blob/master/docs/amazon-sns.md) and also a modification of the main docs using .load() but can't produce a usable SNS object.

``` javascript
var amazon = require('awssum/lib/amazon/amazon');
var snsService = require('awssum/lib/amazon/sns');

// the example says to use snsService.Sns, but this object doesn't exist
console.log('snsService.Sns', snsService.Sns);
// so I tried this
var sns = new SnsService(secretId, secretKey, acctId, region);

console.log('SERVICE', snsService);
console.log('INSTANCE', sns);
```

Produces:

``` javascript
snsService.Sns undefined
SERVICE function (accessKeyId, secretAccessKey, awsAccountId, region) {
    var self = this;

    // call the superclass for initialisation
    Sns.super_.call(this, accessKeyId, secretAccessKey, awsAccountId, region);

    // check the region is valid
    if ( ! endPoint[region] ) {
        throw MARK + "invalid region '" + region + "'";
    }

    return self;
}
INSTANCE { accessKeyId: [Function],
  secretAccessKey: [Function],
  awsAccountId: [Function],
  region: [Function] }

```

And if I try using .load() as the main page suggests:

``` javascript
var amazon = require('awssum').load('amazon/amazon');
var snsService = require('awssum').load('amazon/sns');
var sns = new SnsService(secretId, secretKey, acctId, region);

console.log('SERVICE', snsService);
console.log('INSTANCE', sns);
```

Produces:

``` javascript
SERVICE function (accessKeyId, secretAccessKey, awsAccountId, region) {
    var self = this;

    // call the superclass for initialisation
    Sns.super_.call(this, accessKeyId, secretAccessKey, awsAccountId, region);

    // check the region is valid
    if ( ! endPoint[region] ) {
        throw MARK + "invalid region '" + region + "'";
    }

    return self;
}
INSTANCE { accessKeyId: [Function],
  secretAccessKey: [Function],
  awsAccountId: [Function],
  region: [Function] }
```

Notice that the instance has no createTopic, listTopics, or other methods as described in the API/Example page.

My version info:

``` bash
[root@ ~]$ cat /etc/issue
Amazon Linux AMI release 2011.09

[user@ ~]$ nvm ls
v0.6.4
current:        v0.6.4
default -> v0.6.4

[user@ ~]$ npm ls
application-name@0.0.1 /home/user/
¬ awssum@0.3.3  extraneous
  data2xml@0.4.0
  dateformat@1.0.2-1.2.3
  underscore@1.3.1
  xml@0.0.7
    ¬ xml2js@0.1.13
     sax@0.3.5
```

Hope this helps!

**Comment by chilts** [comment]
Hi katowolf,

Sorry about that but those docs were out of date. I've removed them since it's better to refer to the examples in examples/amazon/sns/*.js

You need to try the .load() method you tried in the latter case and not worry that the console.log(sns) produces a function.

Just start to use the methods you mention on it:

var sns = new snsService(accessKeyId, secretAccessKey, awsAccountId, amazon.US_EAST_1);
sns.ListTopics(function(err, data) {
    // ...etc...
});

Could you try it again and let me know the result? Thanks. :)

Cheers,
Andy

**Comment by katowulf** [comment]
chilts,

Thanks so much for the direction. I tried [this sns test](https://github.com/appsattic/node-awssum/blob/master/examples/amazon/sns/list-topics.js) from examples/amazon/sns and it worked like a charm. Now that I know they are there, I should be all set!

( Still, it's odd that inspecting the sns instance shown none of the methods available : ( )

**Comment by katowulf** [comment]
chilts, if I could also trouble you for a side discussion, what is the proper etiquette on GitHub for questions related to a product? Am I supposed to create issues? Find a mailing list somewhere? I really want to stop being such a noob around here, but node.js was my first intro to the Git world : )

**Comment by chilts** [comment]
Heh, no worries. You can click the 'Message' button at the top of my profile : https://github.com/chilts

I'm not sure the etiquette, but this certainly works. :)
