### ISSUE TITLE
RDS: ModifyDBInstance: "Provide an Engine"

### ISSUE THREAD

**Issue by mikey-** [chilts/awssum#60]
Hey Andy,

Okay, so when I call ModifyDBInstance, I get back the following:

<pre>
Error: {"Code":"AwsSumCheck","Message":"Provide a Engine"}
</pre>

So I took a lil' look in lib/amazon/rds-config.js and saw the following

<pre>
    ModifyDBInstance : {
        defaults : {
            Action : 'ModifyDBInstance'
        },
        args : {
            Action                     : required,
            AllocatedStorage           : optional,
            AllowMajorVersionUpgrade   : optional,
            ApplyImmediately           : optional,
            AutoMinorVersionUpgrade    : optional,
            BackupRetentionPeriod      : optional,
            DBInstanceClass            : optional,
            DBInstanceIdentifier       : required,
            DBParameterGroupName       : optional,
            DBSecurityGroups           : optionalArray,
            <b>Engine                     : required,</b>
            EngineVersion              : optional,
            MasterUserPassword         : required,
            MultiAZ                    : optional,
            OptionGroupName            : optional,
            PreferredBackupWindow      : optional,
            PreferredMaintenanceWindow : optional,
        },
    },
</pre>

According to the aws docs for <a href="http://docs.amazonwebservices.com/AmazonRDS/latest/APIReference/API_ModifyDBInstance.html">ModifyDBInstance</a> there is no Engine parameter and its defs not required. 

Just in case this isn't the problem, here is my cooooode:

<pre>
    //Used to configure a weekly db clone of production. This is specific to our needs at blink
    //todo: accept params for modification rather than hard coded properties
    configureWeeklyDB: function(){
           var Rds = awssum.load('amazon/rds').Rds;
        var rds = new Rds({
            'accessKeyId'         : 'akey',
            'secretAccessKey' : 'skey',
            'region'                     : this.amazon.US_WEST_1
        });
         
        rds.ModifyDBInstance({
            DBInstanceIdentifier    : 'sampleDBIdentifier',
            AllocatedStorage          : 8,
            ApplyImmediately         : true,
            DBSecurityGroups : [
                { Status:'active', DBSecurityGroupName: 'sampleSG-name'}
            ],
            MultiAZ               : false,
            EngineVersion : '5.5.12'
        },
        (function(err,data){
            if(err){
                console.log('Error: ' + JSON.stringify(err));
            }else{
                console.log('Data: ' + JSON.stringify(data));
            }
        }).bind(this));
    },
</pre>

**Comment by mikey-** [comment]
I'm aware you just fixed this but I had just finished typing it out haha. 

I've noticed a few other functions with the Engine param. it might be safe to check all the params to see if they need it (maybe? I can do this later for you. I'm sure you got other shit to do haha)

**Comment by chilts** [comment]
Hi mikey-,

Yeah, no worries. Thanks for raising the issue. Fixed as you say in:
- https://github.com/appsattic/node-awssum/commit/c688f8a598673408f1de18e5bbf43984306b7a3e

Heh, I do have other stuff to do at the moment, just packing to head off to a startup weekend. :) But I should be able to fix little stuff like this on the train in the morning. If you find anything like that extraneous Engine one, just take it out and let me know and I can commit it (unless you want to change it and do a pull-request). ;)

Have fun!

Cheers,
Andy

**Comment by chilts** [comment]
Oh, on another point, I'm putting together a new docs site, for a sneak preview (very alpha) have a look here:
- http://awssum.appsattic.com/

Mind if I steal some of your RDS examples for it? :) I think AwsSum will work only if there are lots of examples which everyone can see rather than having to check the code all the time.

Cheers,
Andy

**Comment by mikey-** [comment]
Oh awesome, that's looking good! 

yeah mans please feel free to use anything I post on here! 

Mikey

**Comment by mikey-** [comment]
Hey Andy, 

Just an update to my example, I was passing the DBSecurityGroups array incorrectly,

It should be like this: <pre>DBSecurityGroups : ['securityGroupName1', 'securityGroupName2', 'etc']</pre>

:)

**Comment by chilts** [comment]
Yep, defined as an array. :)

```
DBSecurityGroups           : optionalArray
```

Sometimes my definitions can be a bit cryptic though, which is why I need the docs site with a load of examples.

Thanks for keeping me informed. :)

Cheers,
Andy
