### ISSUE TITLE
Glacier GetJobOutput fails

### ISSUE THREAD

**Issue by pbinkley** [chilts/awssum#65]
GetJobOutput generates a url without the final "/output" and ignores range, so it retrieves the job description rather than the job output.

**Comment by chilts** [comment]
Hi Peter,

I've just fixed the URL. I think the Range should be okay now since it would have been ignored at the old URL.

Would it be possible to clone master and try again?

Many thanks,
Andy

**Comment by pbinkley** [comment]
Wow!

I'll try it now and let you know.

Peter

**Comment by pbinkley** [comment]
It works. I'm not sure about range though: I tried this:

glacier.GetJobOutput ({ VaultName : 'test', JobId: jobid, Range:
'0-100/493' }, function(err, data) {

but I still got the full inventory (the only job I have available to test
on is a retrieve-inventory). Have I got the right syntax?

Peter

**Comment by chilts** [comment]
Hi Peter,

Can you do me a favour please. Edit lib/awssum.js and find the "var debug = false;" line and make it true. Then re-run your test. AwsSum will output quite a lot of stuff, but somewhere in there are the headers of the request.

Can you paste me the output of those headers, which hopefully should include the 'Range' one. The Range one firstly should be there, and secondly should be your 0-100/493 value.

It should look something like this:

```
  headers: 
   { Range: '0-100/493',
     'x-amz-glacier-version': '2012-06-01',
     'content-type': 'application/x-amz-json-1.1',
     Date: '20120826T044448Z',
     'x-amz-date': '20120826T044448Z',
     Authorization: 'XXX,
     'User-Agent': 'awssum/0.9.0' } }
```

Many thanks for your help on this. :)

Cheers,
Andy

**Comment by pbinkley** [comment]
Hi Andy,

I turned on debug, and the range header is there:

Request Headers:  { range: '0-100/493',
  'x-amz-glacier-version': '2012-06-01',
  'content-type': 'application/x-amz-json-1.1',
  date: '20120826T155512Z',
  'x-amz-date': '20120826T155512Z',
  authorization: '',
  'user-agent': 'awssum/0.9.0',
  host: 'glacier.us-east-1.amazonaws.com' }

I've got a retrieve-archive job now, so I'll try it on that: maybe Amazon
ignores ranges on inventories?

Peter

**Comment by pbinkley** [comment]
Here's what I'm getting when I retrieve an archive. The range is being sent
correctly, but Amazon is ignoring it. My file was just 36 bytes containing
the string "from http://www.glacierfreezer.com/" (I just sent up the file
where I was taking notes on what I was doing), and even when I specify
range 0-10/36 (as in the debug output below) I get the whole body. I'll try
this again when I've uploaded something large enough for range to make
sense.

But anyway, node-awssum is doing its job regarding range. I'm not sure
about the syntax error at the end of this log - it seems that it's trying
to interpret the archive body.

Thanks for looking into this, and for the great work. It's my first
experience with node.js and it definitely won't be my last. I'm blogging
about my tinkering with Glacier for friends in the digital library
community at
http://www.wallandbinkley.com/quaedam/2012/08_25_playing-with-amazon-glacier.htmland
I've put in a plug for node-awssum.

All the best,

Peter

Region               : us-east-1
EndPoint             : glacier.us-east-1.amazonaws.com
AccessKeyId          : AKI...
SecretAccessKey      : 3HO...

## AwsAccountId         :

Request:
- method         :  GET
- protocol       :  https
- host           :  glacier.us-east-1.amazonaws.com
- path           :  /xxxx/vaults/test/jobs/xxxx/output
- params         :  []
- headers        :  { Range: '0-10/36',
  'x-amz-glacier-version': '2012-06-01',
  'content-type': 'application/x-amz-json-1.1',
  Date: '20120826T161918Z',
  'x-amz-date': '20120826T161918Z',
  Authorization: '',
  'User-Agent': 'awssum/0.9.0' }
- forms          :  []
- json           :  {}
- body           :  undefined
  Request:
- statusCode     : 200
- extractHeaders : true

## \- extractBody : json

awssum.js:request(): reqOptions =  { method: 'GET',
  host: 'glacier.us-east-1.amazonaws.com',
  path: '/xxx/vaults/test/jobs/xxx/output',
  headers:
   { Range: '0-10/36',
     'x-amz-glacier-version': '2012-06-01',
     'content-type': 'application/x-amz-json-1.1',
     Date: '20120826T161918Z',
     'x-amz-date': '20120826T161918Z',
     Authorization: 'xxxx,
     'User-Agent': 'awssum/0.9.0' } }
awssum.js:request(): body       =  undefined
Request Headers:  { range: '0-10/36',
  'x-amz-glacier-version': '2012-06-01',
  'content-type': 'application/x-amz-json-1.1',
  date: '20120826T161918Z',
  'x-amz-date': '20120826T161918Z',
  authorization: 'xxxx,
  'user-agent': 'awssum/0.9.0',

##   host: 'glacier.us-east-1.amazonaws.com' }

Response:
- statusCode : 200
- headers : { 'x-amzn-requestid':
  'bo-skCXkNEQsDMLusbWYFf2mhfxQ4Oxldv10tg31DMRlw6g',
  'x-amz-sha256-tree-hash':
  '64c6808abf4f9d90843148dc1b98598da6ec4b997e6816e3a568aaf6d63e0270',
  'accept-ranges': 'bytes',
  'x-amz-archive-description': 'Archived file readme-pbinkley.txt Thu Aug
  23 12:36:41 MDT 2012',
  'content-type': 'application/octet-stream',
  'content-length': '36',
  date: 'Sun, 26 Aug 2012 16:19:18 GMT' }
- body : from http://www.glacierfreezer.com/

---

undefined:1
from http://www.glacierfreezer.com/
 ^
SyntaxError: Unexpected token r
    at Object.parse (native)
    at AwsSum.send
(/Users/peterbinkley/data/glacier/nodejs-test/node_modules/awssum/lib/awssum.js:767:32)
    at _.once
(/Users/peterbinkley/data/glacier/nodejs-test/node_modules/awssum/node_modules/underscore/underscore.js:576:26)
    at IncomingMessage.AwsSum.request
(/Users/peterbinkley/data/glacier/nodejs-test/node_modules/awssum/lib/awssum.js:877:13)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete](http.js:149:23)
    at CleartextStream.socketOnData [as ondata](http.js:1366:20)
    at CleartextStream.CryptoStream._push (tls.js:485:27)
    at SecurePair.cycle (tls.js:839:20)

**Comment by chilts** [comment]
Hi Peter,

Yes, you've found another bug. I didn't put in the directive to say to AwsSum that the returned body is just a blob, rather than some structured data which should be interpreted (like XML or JSON). It's an easy fix, but I'll reopen this issue and close it with the commit.

Many thanks for your continued investigations. They're much appreciated. :)

Cheers,
Andy
