### ISSUE TITLE
Convert DynamoDB to use AWS Signature v4 (instead of the STS service)

### ISSUE THREAD

**Issue by chilts** [chilts/awssum#67]
DynamoDB now supports AWS Signature v4:
- http://docs.amazonwebservices.com/amazondynamodb/latest/developerguide/MakingHTTPRequests.html

Also, some reference can be gained here, which is a little bizarre:
- https://github.com/appsattic/node-awssum/pull/64

Should make the code in lib/amazon/dynamodb.js a little more straightforward too. :)

**Comment by mweagle** [comment]
Excellent - thanks for this much improved solution to the copy-n-paste "fix" :)
