### ISSUE TITLE
options for CloudSearch

### ISSUE THREAD

**Issue by dmcbeath** [chilts/awssum#70]
In the cloudsearch.js file, could you please add other search options such as 'size', 'start', 'return-fields', etc.?

```
Search : {
    args : {
        'q' : { required : false, type : 'param' },
        'size' : { required : false, type : 'param' },
    }
},
```

**Comment by chilts** [comment]
Hi Darin,

Many thanks for this. I started coding this up yesterday, but the 'FACET' stuff is a little annoying since Amazon have created a whole new way of doing this (usually they don't put the 'name' into the parameter, name, but instead have it as a value).

Anyway, I've got some code, it's 90% working and I just need to add a few more tests. I should be able to finish it off later on today so I'll let you know on here. :)

Thanks for raising this issue.

Cheers,
Andy

**Comment by chilts** [comment]
Hi Darin,

I've just committed a fix for this, but please re-test and let me know how it goes. I've managed to do some testing but not enough. :)

Have a look here to see how to do the facets:
- https://github.com/appsattic/node-awssum/blob/master/examples/amazon/cloudsearch/search.js

Many thanks,
Andy

**Comment by chilts** [comment]
Hi @dmcbeath,

Any luck trying this out. Would love to hear that you've had some success. :)

Cheers,
Andy

**Comment by dmcbeath** [comment]
Will test on tuesday.  Holiday weekend in the us :-)

Sent from my iPhone

On Sep 1, 2012, at 1:54 AM, "Andrew Chilton" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @dmcbeathhttps://github.com/dmcbeath,

Any luck trying this out. Would love to hear that you've had some success. :)

Cheers,
Andy

**Comment by dmcbeath** [comment]
Initial/limited testing shows that this is working fine.

Darin.

From: <McBeath>, Darin McBeath <d.mcbeath@elsevier.com<mailto:d.mcbeath@elsevier.com>>
Date: Saturday, September 1, 2012 9:30 AM
To: appsattic/node-awssum <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: Re: [node-awssum] options for CloudSearch (#70)

Will test on tuesday.  Holiday weekend in the us :-)

Sent from my iPhone

On Sep 1, 2012, at 1:54 AM, "Andrew Chilton" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @dmcbeathhttps://github.com/dmcbeath,

Any luck trying this out. Would love to hear that you've had some success. :)

Cheers,
Andy

**Comment by chilts** [comment]
Excellent, thanks Darin! :)

Cheers,
Andy
