### ISSUE TITLE
ACLs are broken for all operations involving ACLs

### ISSUE THREAD

**Issue by chilts** [chilts/awssum#84]
Hey Andy,

here's one example XML generated with s3cmd. It sets READ for everyone. This is the same as a canned ACL : public-read. If you would want public write as well you would add another <grant> for that.
You have two types of users, CononicalUser (like the owner of the object) and Group (Like EveryOne or authenticatedUsers).

var everyone = 'http://acs.amazonaws.com/groups/global/AllUsers';
var authenticatedUsers = 'http://acs.amazonaws.com/groups/global/AuthenticatedUsers';
http://docs.amazonwebservices.com/AmazonS3/latest/dev/ACLOverview.html

s3cmd setacl --acl-public s3://files/test.png

PUT /test.png?acl HTTP/1.1
Host: files.demo.scality.com
Accept-Encoding: identity
content-length: 585
Authorization: AWS XXX:XXX=
x-amz-date: Thu, 16 Aug 2012 09:41:02 +0000

<AccessControlPolicy
xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Owner><ID>XXX</ID></Owner>
<AccessControlList>
<Grant>
<Grantee
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:type="CanonicalUser"><ID>XXX</ID></Grantee><Permission>FULL_CONTROL</Permission></Grant>
<Grant>
<Grantee
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:type="Group"><URI>http://acs.amazonaws.com/groups/global/AllUsers</URI>
</Grantee>
<Permission>READ</Permission>
</Grant>
</AccessControlList>
</AccessControlPolicy>

HTTP/1.1 200 OK
Date: Thu, 16 Aug 2012 09:41:02 GMT
Server: RestServer/1.0
Content-Length: 0
Content-Type: binary/octet-stream
Cache-Control: no-cache
Connection: keep-alive

cheers
Eiki

**Comment by chilts** [comment]
I've just landed the ACL stuff in master. It'd be great if you could check it out and see how it works for you. Please take a look at the examples here:
- http://awssum.io/amazon/s3/put-bucket-acl.html

(Yep, I finally have a good process for the docs site.) :)

There is also tests in test/integration-s3 and also an example in examples/amazon/s3/put-bucket-acl.js.

Note: whilst digging further, I also noticed all of the x-amz-grant-\* headers which I've also added. Operations include PutBucket, PutBucketAcl, PutObject, PutObjectAcl and CopyObject.

**Comment by laddi** [comment]
Sadly, this doesn't work for us.  We don't really know what is wrong but we are getting a 502 Bad Gateway response from our S3 server but it works fine when going through Cyberduck so we suspect it's something in awssum, missing header or something like that...

Furthermore, when trying to use the headers and body directly (from awssum debug) in a RestFUL client test, it returns a SignatureDoesNotMatch (403) error.

**Comment by chilts** [comment]
Please paste exactly the code you are using. And also specify what you are trying to achieve.

Cheers,
Andy

**Comment by laddi** [comment]
Here are the options I'm sending into PutObjectAcl to add READ permission for all users:

```
objectOptions = {
    BucketName : bucketName,
    ObjectName: objectName,
    AccessControlPolicy: {
        _attr: { xmlns: "http://s3.amazonaws.com/doc/2006-03-01/" },
        AccessControlList: {
                Grant: [
                        {
                    Permission: 'FULL_CONTROL',
                    Grantee: {
                        ID: granteeID,
                        _attr: { 'xsi:type': 'CanonicalUser', 'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance' },
                    }
                },
                {
                    Permission: 'READ',
                    Grantee: {
                        URI: 'http://acs.amazonaws.com/groups/global/AllUsers',
                        _attr: { 'xsi:type': 'Group', 'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance' }
                    }
                }
            ]
            },
            Owner: {
                ID: granteeID
            }
    }
};
```

This is the debug from awssum:

```
Request:
- method         :  PUT
- protocol       :  https
- host           :  12buckettest.s.greenqloud.com
- path           :  /JKB.jpg
- params         :  [ { name: 'acl', value: undefined } ]
- headers        :  { Date: 'Wed, 26 Sep 2012 19:57:40 UTC',
  Authorization: 'AWS cUFFbGNyanZnZlM2S0pGZlNoQ0xpN2ljWkxnV3hD:d2Grv8Ykqwqa6fdn143WiW2qyJo=',
  'User-Agent': 'awssum/0.11.0' }
- forms          :  []
- json           :  {}
- body           :  <?xml version="1.0" encoding="utf-8"?>
<AccessControlPolicy xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><AccessControlList><Grant>     <Permission>FULL_CONTROL</Permission><Grantee xsi:type="CanonicalUser" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><ID>C04814737E5173C4C04814000000004000000120</ID></Grantee></Grant></AccessControlList><Owner><ID>C04814737E5173C4C04814000000004000000120</ID></Owner></AccessControlPolicy>
Request:
- statusCode     : 200
- extractHeaders : true
- extractBody : none
```

And this is the response:

```
Response:
- statusCode : 502
- headers : { 'cache-control': 'no-cache',
  connection: 'close',
  'content-type': 'text/html' }
- body : <html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>
```

**Comment by sputnick** [comment]
Just to add. When Laddi tried doing the same request with Rest tester plugin http://restclient.net/ he got a signature error...

**Comment by sputnick** [comment]
Here is a TCP dump of a successful ACL update from s3cmd I got with "sudo ngrep -d en1 -W byline port 80" (installed ngrep with brew on the mac). And then the awssum stuff that fails. Maybe you can spot the difference. I think it is a most likely a signature bug or missing headers problem (x-amz-date, Accept-Encoding: identity, content-length and Date header removed). When I try adding some of the headers I get a signature error.

## s3cmd:

#######
T 192.168.100.246:63500 -> 46.149.16.21:80 [AP]
GET /screeny.png?acl HTTP/1.1.
Host: newestbucket.s.greenqloud.com.
Accept-Encoding: identity.
content-length: 0.
Authorization: AWS cUFFbGNyanZnZlM2S0pGZlNoQ0xpN2ljWkxnV3hD:xVBvf6sQSIi92OfMz+7RQalP0zg=.
x-amz-date: Thu, 27 Sep 2012 17:50:18 +0000.
.

##
T 46.149.16.21:80 -> 192.168.100.246:63500 [AF]
HTTP/1.1 200 OK.
Date: Thu, 27 Sep 2012 17:50:18 GMT.
Server: RestServer/1.0.
Content-Length: 568.
Content-Type: application/xml.
Cache-Control: no-cache.
Connection: close.
.
<?xml version="1.0" encoding="UTF-8"?>
<AccessControlPolicy xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>C04814737E5173C4C04814000000004000000120</ID>
<DisplayName>59d9785c_e7ef_4633_b16c_e045532a4b0b</DisplayName>
</Owner>
<AccessControlList><Grant><Grantee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="CanonicalUser"><ID>C04814737E5173C4C04814000000004000000120</ID>
<DisplayName>59d9785c_e7ef_4633_b16c_e045532a4b0b</DisplayName>
</Grantee>
<Permission>FULL_CONTROL</Permission>
</Grant>
</AccessControlList>
</AccessControlPolicy>

#######
T 192.168.100.246:63501 -> 46.149.16.21:80 [AP]
PUT /screeny.png?acl HTTP/1.1.
Host: newestbucket.s.greenqloud.com.
Accept-Encoding: identity.
content-length: 585.
Authorization: AWS cUFFbGNyanZnZlM2S0pGZlNoQ0xpN2ljWkxnV3hD:tEmvMoRYGpY/zNyDM3qsFdM860s=.
x-amz-date: Thu, 27 Sep 2012 17:50:18 +0000.
.
<AccessControlPolicy xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>C04814737E5173C4C04814000000004000000120</ID></Owner><AccessControlList><Grant><Grantee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="CanonicalUser"><ID>C04814737E5173C4C04814000000004000000120</ID></Grantee><Permission>FULL_CONTROL</Permission></Grant><Grant><Grantee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Group"><URI>http://acs.amazonaws.com/groups/global/AllUsers</URI></Grantee><Permission>READ</Permission></Grant></AccessControlList></AccessControlPolicy>
#
T 46.149.16.21:80 -> 192.168.100.246:63501 [AF]
HTTP/1.1 200 OK.
Date: Thu, 27 Sep 2012 17:50:18 GMT.
Server: RestServer/1.0.
Content-Length: 0.
Content-Type: application/octet-stream.
Cache-Control: no-cache.
Connection: close.
.

###^Cexit

## awssum

T 192.168.100.246:57746 -> 46.149.16.11:80 [AP]
PUT /screeny.png?acl HTTP/1.1.
Accept-Encoding: identity.
x-amz-date: Thu, 27 Sep 2012 19:46:39 UTC.
Date: Thu, 27 Sep 2012 19:46:39 UTC.
Authorization: AWS cUFFbGNyanZnZlM2S0pGZlNoQ0xpN2ljWkxnV3hD:CDoacFygbGH/ELY6jXAKCRecR08=.
User-Agent: awssum/0.10.1.
Host: newestbucket.s.greenqloud.com.
Connection: keep-alive.
Transfer-Encoding: chunked.
.
2b0.
<?xml version="1.0" encoding="utf-8"?>
<AccessControlPolicy xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><AccessControlList><Grant><Permission>FULL_CONTROL</Permission><Grantee xsi:type="CanonicalUser" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><ID>C04814737E5173C4C04814000000004000000120</ID></Grantee></Grant><Grant><Permission>WRITE</Permission><Grantee xsi:type="Group" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><URI>http://acs.amazonaws.com/groups/global/AllUsers</URI></Grantee></Grant></AccessControlList><Owner><ID>C04814737E5173C4C04814000000004000000120</ID><DisplayName>59d9785c_e7ef_4633_b16c_e045532a4b0b</DisplayName></Owner></AccessControlPolicy>.
0.
.

#
T 46.149.16.11:80 -> 192.168.100.246:57746 [AF]
HTTP/1.1 403 Forbidden.
Date: Thu, 27 Sep 2012 19:46:39 GMT.
Server: RestServer/1.0.
Content-Length: 110.
Content-Type: application/xml.
Cache-Control: no-cache.
Connection: close.
.
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code>
<Message></Message>
</Error>

**Comment by chilts** [comment]
Hi Guys,

When I do the following request to Amazon S3, it works completely fine. See the examples/amazon/s3/put-object-acl.js file for the test. Can you try it for me. I can PM you my canonical user id if you like. Note: it's a 64 char one alphanumeric one, not the 12 char number.

I don't get a signature error, nor a 502. It gives me the response shown below. Are you doing this against Amazon S3 or your own S3 service?

```
var fullControlReadAll = {
    BucketName : 'pie-18',
    ObjectName : 'test-object-for-complex-acl.txt',
    AccessControlPolicy: {
        AccessControlList: {
            Grant: [
                {
                    Permission: 'FULL_CONTROL',
                    Grantee: {
                        EmailAddress : 'admin@appsattic.com',
                        _attr : {
                            'xsi:type' : 'AmazonCustomerByEmail',
                            'xmlns:xsi' : 'http://www.w3.org/2001/XMLSchema-instance',
                        },
                    },
                },
                {
                    Permission: 'FULL_CONTROL',
                    Grantee: {
                        // still me
                        ID : 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                        _attr : {
                            'xsi:type' : 'CanonicalUser',
                            'xmlns:xsi' : 'http://www.w3.org/2001/XMLSchema-instance',
                        },
                    },
                },
                {
                    Permission: 'READ',
                    Grantee: {
                        URI : 'http://acs.amazonaws.com/groups/global/AllUsers',
                        _attr : {
                            'xsi:type' : 'Group',
                            'xmlns:xsi' : 'http://www.w3.org/2001/XMLSchema-instance',
                        },
                    },
                },
            ],
        },
        Owner: {
            ID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        }
    }
};

s3.PutObjectAcl(fullControlReadAll, function(err, data) {
    fmt.msg("putting an object with an AccessControlPolicy to pie-18 - expecting success");
    fmt.dump(err, 'Error');
    fmt.dump(data, 'Data');
});
```

Response:

```
Error : null
Data : { StatusCode: 200,
  Headers: 
   { 'x-amz-id-2': 'YYFU1kHaGkxURRazJlsAuZLgiKnGlbmrYsghpSihz6bYzrde2ByISvzgF6UyRkyo',
     'x-amz-request-id': 'E9DD8E4393AACD11',
     date: 'Sat, 29 Sep 2012 09:21:27 GMT',
     'content-length': '0',
     server: 'AmazonS3' },
  Body: '' }
```

Eiriki: that UTF8 bug is not related to this issue. Can you raise another bug for me containing details, thanks.

Cheers,
Andy

**Comment by chilts** [comment]
Oopse, meant to leave it open.

**Comment by chilts** [comment]
Note: I can't test against your s.greenqloud.com since your system expired my account (for some reason).

**Comment by sputnick** [comment]
We are using it against our Storage Qloud service not AWS. I will get your account reactivated. Btw. we don't support the email type yet. I'm just trying to get a everyone read in addition to the owner full control.

**Comment by laddi** [comment]
This works fine now so you can close this issue... :)

**Comment by sputnick** [comment]
Just echoing Laddi. This works fine now.
