### ISSUE TITLE
S3 DeleteMultipleObjects - SignatureDoesNotMatch

### ISSUE THREAD

**Issue by scohen28** [chilts/awssum#88]
When batching up objects for deletion I'm seeing approx. 6 out of 10 requests rejected with a 403 - SignatureDoesNotMatch return result, even though nothing has changed with the signature and/or clock setting.

I'm using the awssum library in a Node.js process where objects to be deleted are retrieved from an SQS queue.  I've pre-created the s3 object as follows and cache it for all requests:

var s3 = new S3({
    'accessKeyId' : creds.akey,
    'secretAccessKey' : creds.skey,
    'awsAccountId' : creds.acctId,
    'region' : creds.region
});

Is there something else I should be checking for (repeatedly resubmitting the batch will eventually succeed, but my concern is the high number of rejects with this error).

**Comment by chilts** [comment]
Hiya,

Thanks for raising this issue. Can you let me know what versions of Node.js and AwsSum you are using?

This sounds like it might be something different in what is being sent to S3. What kind of ObjectNames are you passing, any that are different to the rest? What I'm looking for is any special characters or UTF8 characters or anything like that.

Is it possible for you to paste me _exactly_ what you are passing to s3.DeleteMultipleObjects() so I can try and recreate. :)

The way you are creating the s3 object and re-using it is perfectly fine.

Cheers,
Andy

**Comment by scohen28** [comment]
Andy,

  The ObjectNames look like this:

```
            ‘sea-staging/bb9org/ebrown/f2ead2a1-0477-4c55-9f28-935613496769/e2@e.com/9df274c3-a366-4e1e-ab8c-b7c91586e611/desktopphotos/desktop_111214_174316.jpeg’,
```

‘sea-staging/bb9org/ebrown/f2ead2a1-0477-4c55-9f28-935613496769/e2@e.com/9df274c3-a366-4e1e-ab8c-b7c91586e611/desktopphotos/desktop_111214_174321.jpeg’,
Etc.

Essentially, I’m enumerating through a bucket with a prefix and deleting all items – e.g., delete “folder” – all items basically are composed of strings with no special characters (ASCII character set as UTF-8)

Shmuel

**Comment by chilts** [comment]
Hi Shmuel,

Cool, thanks. I'll go and try a test with the '@' character in an ObjectName. I have a sneaking suspicion that that might be the problem. :)

Thanks and I'll report back later.

Cheers,
Andy

**Comment by scohen28** [comment]
Great – thanks!

**Comment by chilts** [comment]
Ah, it's not the '@' char, I just did a PutObject(). I'll try it with a DeleteMultipleObjects() later. Train just getting into station. :)

Andy

**Comment by chilts** [comment]
Hiya,

Can you paste me exactly what you're passing to s3.DeleteMultipleObjects().

This works for me and I need to figure out what you're doing ... sorry, I currently don't have any visibility of that yet. I should have asked you this at the start! :)

```
var options = {
    BucketName : 'pie-18',
    Objects : [
        'nothing-here.txt',
        { Key : 'another-missing-file.txt' },
    ]
};
```

This will delete 2 files. The 2nd item in this list can be used to delete an object with a 'VersionId' too. :)

Cheers,
Andy

**Comment by scohen28** [comment]
Andrew,

I’ll get a full set later today (after I’m done with meetings) – my suspicion is that one of the “Objects” array value gets ‘undefined’ as its value, instead of a uri string – just a hunch right now, but I think that may throw off the call.

Shmuel

**Comment by scohen28** [comment]
I've confirmed that if one of the values in my 'Objects' array is null or undefined, the 'SignatureDoesNotMatch' is the error returned.

**Comment by chilts** [comment]
Hi Shmuel,

I confirmed for myself that if one of the keys was missing, having undefined as the filename didn't cause any problems. I've committed just a fix for the examples/ but no code changes.

Can you retry for me or let me know if you have found any more information?

Many thanks,
Andy
