### ISSUE TITLE
CloudWatch not working?

### ISSUE THREAD

**Issue by ghost** [chilts/awssum#90]
I'm trying to use the CloudWatch Amazon module and not having a lot of luck.  Am I doing something wrong?  My code is:

``` javascript
var awssum = require('awssum');
var amazon = awssum.load('amazon/amazon');
var CloudWatch = awssum.load('amazon/cloudwatch').CloudWatch;
var cloudwatch = new CloudWatch({
  'accessKeyId'     : 'ACCESSKEY',
  'secretAccessKey' : 'SECRETKEY',
  'region'          : amazon.US_EAST_1
});

var dayInMilliseconds = 1000 * 60 * 60 * 24;
var hourInMilliseconds = 1000 * 60 * 60;
var endTime = new Date();
var startTime = new Date(endTime.getTime() - hourInMilliseconds);
var stats = {
  MetricName: 'CPUUtilization',
  Statistics: [ 'Average' ],
  Namespace:  'AWS/EC2',
  StartTime:  startTime.toISOString(),
  EndTime:    endTime.toISOString(),
  Period:     60,
  Unit:       'Percent'
};
cloudwatch.GetMetricStatistics(stats, function(error, result) {
  console.log(result.Body.GetMetricStatisticsResponse.GetMetricStatisticsResult.Datapoints);
});

```

I was able to retrieve the list of metrics available through your API which is how I determined the `MetricName` and `Namespace` to use.  But retrieving the actual value results in an empty Javascript object `{}` being returned instead of an array of vaiues.

Thanks in advance!

**Comment by chilts** [comment]
Hiya Paul,

Are you sure you have some metrics in there? I.e. if you have an empty list maybe there is nothing there (sorry, am stating the obvious). :)

If you can, can you edit your ./node_modules/awssum/lib/awssum.js and set debug to be 'true' and re-try. And if possible, paste some of that output here so I can see what is going on. You should be able to see where the headers/params are.

Many thanks,
Andy

P.S. I'll go and try this later and report back. :)

**Comment by ghost** [comment]
I had thought of that!  :-)  CloudWatch produces ten statistics at five minute intervals for free just because you're running an EC2 instance.  When I view the VM in the AWS admin panel, there is a graph below the instance with the historical CPU load, memory load, and so forth.  When I plug the various `MetricNames` into my code, all I get back is an empty JavaScript object like this:

``` javascript
ubuntu@domU:/tmp/$ node test.js 
{ '@': { xmlns: 'http://monitoring.amazonaws.com/doc/2010-08-01/' },
  GetMetricStatisticsResult: { Datapoints: {}, Label: 'CPUUtilization' },
  ResponseMetadata: { RequestId: 'a41b0f90-0ee6-11e2-96d3-b3b49bc1be8d' } }
```

The `console.log` argument was changed to `result.Body.GetMetricStatisticsResponse` so you can see more of the object.

Setting `debug=true` results in the following:

```
ubuntu@domU:/tmp$ node test.js
-------------------------------------------------------------------------------
Request:
- method         :  GET
- protocol       :  https
- host           :  monitoring.us-east-1.amazonaws.com
- path           :  /
- params         :  [ { name: 'Action', value: 'GetMetricStatistics' },
  { name: 'EndTime', value: '2012-10-05T12:28:00.351Z' },
  { name: 'MetricName', value: 'CPUUtilization' },
  { name: 'Namespace', value: 'AWS/EC2' },
  { name: 'Period', value: 60 },
  { name: 'StartTime', value: '2012-10-05T11:28:00.351Z' },
  { name: 'Statistics.member.1', value: 'Average' },
  { name: 'Unit', value: 'Percent' },
  { name: 'AWSAccessKeyId', value: 'ACCESSKEYID' },
  { name: 'SignatureVersion', value: 2 },
  { name: 'SignatureMethod', value: 'HmacSHA256' },
  { name: 'Timestamp', value: '2012-10-05T12:28:00.352Z' },
  { name: 'Version', value: '2010-08-01' },
  { name: 'Signature',
    value: 'SS59+RYaIQcVnK1YTB35XQtUWAz51aQz99RwubFkwi0=' } ]
- headers        :  { 'User-Agent': 'awssum/0.11.0' }
- forms          :  []
- json           :  {}
- body           :  undefined
Request:
- statusCode     : 200
- extractHeaders : true
- extractBody : xml
-------------------------------------------------------------------------------
awssum.js:request(): reqOptions =  { method: 'GET',
  host: 'monitoring.us-east-1.amazonaws.com',
  path: '/?Action=GetMetricStatistics&EndTime=2012-10-05T12%3A28%3A00.351Z&MetricName=CPUUtilization&Namespace=AWS%2FEC2&Period=60&StartTime=2012-10-05T11%3A28%3A00.351Z&Statistics.member.1=Average&Unit=Percent&AWSAccessKeyId=ACCESSKEYID&SignatureVersion=2&SignatureMethod=HmacSHA256&Timestamp=2012-10-05T12%3A28%3A00.352Z&Version=2010-08-01&Signature=SS59%2BRYaIQcVnK1YTB35XQtUWAz51aQz99RwubFkwi0%3D',
  headers: { 'User-Agent': 'awssum/0.11.0' } }
awssum.js:request(): body       =  undefined
Request Headers:  { 'user-agent': 'awssum/0.11.0',
  host: 'monitoring.us-east-1.amazonaws.com' }
-------------------------------------------------------------------------------
Response:
- statusCode : 200
- headers : { 'x-amzn-requestid': '70ac4b48-0ee7-11e2-af3d-47ab5a623870',
  'content-type': 'text/xml',
  'content-length': '337',
  date: 'Fri, 05 Oct 2012 12:23:15 GMT' }
- body : <GetMetricStatisticsResponse xmlns="http://monitoring.amazonaws.com/doc/2010-08-01/">
  <GetMetricStatisticsResult>
    <Datapoints/>
    <Label>CPUUtilization</Label>
  </GetMetricStatisticsResult>
  <ResponseMetadata>
    <RequestId>70ac4b48-0ee7-11e2-af3d-47ab5a623870</RequestId>
  </ResponseMetadata>
</GetMetricStatisticsResponse>

-------------------------------------------------------------------------------
{ '@': { xmlns: 'http://monitoring.amazonaws.com/doc/2010-08-01/' },
  GetMetricStatisticsResult: { Datapoints: {}, Label: 'CPUUtilization' },
  ResponseMetadata: { RequestId: '70ac4b48-0ee7-11e2-af3d-47ab5a623870' } }
```

**Comment by chilts** [comment]
Hmm, I've been trying this over the past few days and can't get anything out either. I don't think this is specific to AwsSum though since a number of people have problems on the forums. I think we need to figure out exactly what params and values the service is requesting.

I'll keep trying over the next few days and report back if I find anything.

Cheers,
Andy

**Comment by ghost** [comment]
Andy,

After banging my head against the wall trying to figure this out, I had a stroke of luck! Amazon provides the `Dimensions` parameter which is used to filter the results in a variety of ways. By default, a CloudWatch request that does not include a `Dimensions` parameter will query all instances you have running under your account. The problem with this is, only machines that have enhanced monitoring enabled (e.g. not free) will respond to such a request.

The answer is: To receive a response from a single instance, you must explicitly use a filter to specify that instance.

Although this works, I think it's really backwards. The default query is virtually guaranteed to fail for most people, but there you go. Just add `Dimensions: [{ Name: 'InstanceId', Value: 'i-fake1234' }]` to the parameter list.

Thanks,
-Paul

**Comment by chilts** [comment]
Oh wow! Fantastic. Man, this puzzled me for quite a while and I went quiet on it 'coz I had no idea how to fix it.

Ok, I'm gonna try this myself later ... and a huge thanks for reporting back since I'm sure it'll trip a lot of people up too.

Great stuff. :D

Cheers,
Andy

**Comment by ghost** [comment]
I think you might be able to avoid confusion by making `Dimensions` a special-case required parameter. The user must pass the parameter but the value must be an empty object `{}` to signify that they really want the "query all instances" behavior. You'd have to remove the `Dimensions` parameter from the actual AWS `GET` invocation in this situation, but it would make your API cleaner and avoid a lot of confusion.

My suggestion would be to make the error message something like, "Dimensions is a required parameter. If you really mean to query all of your running instances, specify an empty object {} as the value of this parameter."

I realize that this would make your implementation code a little less straightforward, but it might be worth it in the long run.

Let me know what you think!

-Paul

**Comment by chilts** [comment]
Hi Paul,

Yeah, we need to do something but I'm loath to patch the Amazon API - if we start, where do we stop? AwsSum is intended as a low-level library and a one-to-one relationship with each service/operations and generally (but not always) that's the case for parameters too.

Instead, a largish note should be added to the docs so that when people come by it they'll see what the gotchya is. Plus the examples should also show this. :)

Many thanks again for your investigation into this.

Cheers,
Andy

**Comment by ghost** [comment]
Where do you stop? When their API finally makes sense. I guess you'll never be without work...  ;-)

Documentation is probably the best bet in this case. Feel free to use my sample code in your example. I made it as minimal as possible, so it should be a good fit to include with your distribution.

-Paul

**Comment by techtribe** [comment]
@chilts will have a look to add this to the docs in the coming days. FYI
