### ISSUE TITLE
Wrong required parameter in ModifyInstanceAttribute (EC2)

### ISSUE THREAD

**Issue by laddi** [chilts/awssum#98]
The function requires an ImageId parameter but should use an InstanceId parameter instead.

**Comment by chilts** [comment]
Thanks Laddi. Pushed to master. Will be in the next release.

**Comment by sputnick** [comment]
Thanks Andy, when is the next release due? We would rather not be updating to master with git on production.

cheers
Eiki

**Comment by laddi** [comment]
Just a bump on @sputnick's comment, since we are only using releases of awssum in our app.  Also, the 'fix' I suggested in issue #111 would be a huge boost for us since it completely fixes all our ACL problems... :)

Regards,
Laddi.
